//! Every menu / keyboard action, named after GitHub Desktop's menu items.

gpui_kit::actions!(
    corvane,
    [
        // Lists (arrow keys while the changes list has focus)
        SelectNextFile,
        SelectPreviousFile,
        SelectAllFiles,
        // Commit form context menu (spelling suggestions are picked by index)
        SpellSuggestion0,
        SpellSuggestion1,
        SpellSuggestion2,
        SpellSuggestion3,
        SpellSuggestion4,
        SpellAddToDictionary,
        ToggleCommitSpellcheck,
        // Compare-to-branch filter box
        CompareSelect,
        CompareClear,
        // History keyboard reorder mode
        ReorderMoveUp,
        ReorderMoveDown,
        ReorderConfirm,
        ReorderCancel,
        // App menu
        About,
        OpenSettings,
        InstallCli,
        Hide,
        HideOthers,
        ShowAll,
        Quit,
        // File
        NewRepository,
        AddLocalRepository,
        CloneRepository,
        // Edit
        Undo,
        Redo,
        Cut,
        Copy,
        Paste,
        SelectAll,
        Find,
        // View
        ShowChanges,
        ShowHistory,
        ShowRepositoryList,
        ShowBranchesList,
        GoToSummary,
        ToggleStashedChanges,
        ToggleChangesFilter,
        ToggleFullScreen,
        ResetZoom,
        ZoomIn,
        ZoomOut,
        ExpandActiveResizable,
        ContractActiveResizable,
        // Repository
        Push,
        Pull,
        Fetch,
        RemoveRepository,
        ViewOnGitHub,
        OpenInShell,
        ShowInFinder,
        OpenInEditor,
        OpenWith,
        CreateIssue,
        RepositorySettings,
        // Branch
        NewBranch,
        RenameBranch,
        DeleteBranch,
        DiscardAllChanges,
        StashAllChanges,
        UpdateFromDefaultBranch,
        CompareToBranch,
        MergeIntoCurrentBranch,
        SquashAndMergeIntoCurrentBranch,
        RebaseCurrentBranch,
        CompareOnGitHub,
        ViewBranchOnGitHub,
        PreviewPullRequest,
        CreatePullRequest,
        // Window
        Minimize,
        Zoom,
        CloseWindow,
        BringAllToFront,
        // Help
        ReportIssue,
        ContactSupport,
        ShowUserGuides,
        ShowKeyboardShortcuts,
        ShowLogs,
        // In-app
        Commit,
        ToggleSection,
        CloseFoldout,
    ]
);
