// Generated by tools/ts-queries/gen.py from tools/ts-queries/languages.toml; do not edit.

#[cfg(feature = "lang-asciidoc")]
extern crate tree_sitter_asciidoc;
#[cfg(feature = "lang-fish")]
extern crate tree_sitter_fish;
#[cfg(feature = "lang-less")]
extern crate tree_sitter_less;
#[cfg(feature = "lang-scss")]
extern crate tree_sitter_scss;
#[cfg(feature = "lang-vim")]
extern crate tree_sitter_vim;
#[cfg(feature = "lang-wit")]
extern crate tree_sitter_wit;

grammars! {
    "ada" ("lang-ada") => tree_sitter_ada::LANGUAGE,
        extensions: ["ads", "adb", "ada"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "agda" ("lang-agda") => tree_sitter_agda::LANGUAGE,
        extensions: ["agda", "lagda"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "angular")]
    "angular" ("lang-angular") => c_language!(tree_sitter_angular),
        extensions: ["component.html"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript", "json", "regex"];
    #[cfg(corvane_src = "apex")]
    "apex" ("lang-apex") => c_language!(tree_sitter_apex),
        extensions: ["cls", "trigger", "apex"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "javadoc"];
    #[cfg(corvane_src = "arduino")]
    "arduino" ("lang-arduino") => c_language!(tree_sitter_arduino),
        extensions: ["ino"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen", "printf", "re2c"];
    "asciidoc" ("lang-asciidoc") => c_language!(tree_sitter_asciidoc),
        extensions: ["adoc", "asciidoc", "asc"],
        filenames: [],
        first_line: "",
        aliases: ["adoc"],
        injects: [];
    "asm" ("lang-asm") => tree_sitter_asm::LANGUAGE,
        extensions: ["asm", "s"],
        filenames: [],
        first_line: "",
        aliases: ["assembly", "nasm"],
        injects: ["comment"];
    #[cfg(corvane_src = "astro")]
    "astro" ("lang-astro") => c_language!(tree_sitter_astro),
        extensions: ["astro"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript", "json", "regex", "scss", "typescript"];
    #[cfg(corvane_src = "authzed")]
    "authzed" ("lang-authzed") => c_language!(tree_sitter_authzed),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "awk")]
    "awk" ("lang-awk") => c_language!(tree_sitter_awk),
        extensions: ["awk", "auk", "gawk", "mawk", "nawk"],
        filenames: [],
        first_line: r"^#!.*\b(awk|gawk|mawk|nawk)\b",
        aliases: [],
        injects: ["comment", "printf", "regex"];
    "bash" ("lang-bash") => tree_sitter_bash::LANGUAGE,
        extensions: ["sh", "bash", "ebuild", "eclass", "bats", "command", "ksh"],
        filenames: [".bashrc", ".bash_profile", ".bash_login", ".bash_logout", ".profile", "bashrc", ".envrc", "pkgbuild", "apkbuild"],
        first_line: r"^#!.*\b(bash|sh|dash|ksh|mksh)\b",
        aliases: ["sh", "shell", "shellscript"],
        injects: ["comment", "printf", "readline", "regex"];
    #[cfg(corvane_src = "bass")]
    "bass" ("lang-bass") => c_language!(tree_sitter_bass),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "beancount")]
    "beancount" ("lang-beancount") => c_language!(tree_sitter_beancount),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "bibtex")]
    "bibtex" ("lang-bibtex") => c_language!(tree_sitter_bibtex),
        extensions: ["bib", "bibtex"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "bicep" ("lang-bicep") => tree_sitter_bicep::LANGUAGE,
        extensions: ["bicep", "bicepparam"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "bitbake")]
    "bitbake" ("lang-bitbake") => c_language!(tree_sitter_bitbake),
        extensions: ["bb", "bbappend", "bbclass"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment", "regex"];
    #[cfg(corvane_src = "blade")]
    "blade" ("lang-blade") => c_language!(tree_sitter_blade),
        extensions: ["blade", "blade.php"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript", "json", "php_only", "python", "regex", "toml"];
    #[cfg(corvane_src = "bp")]
    "bp" ("lang-bp") => c_language!(tree_sitter_bp),
        extensions: ["bp"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "bpftrace")]
    "bpftrace" ("lang-bpftrace") => c_language!(tree_sitter_bpftrace),
        extensions: ["bt"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["c", "comment"];
    #[cfg(corvane_src = "brightscript")]
    "brightscript" ("lang-brightscript") => c_language!(tree_sitter_brightscript),
        extensions: ["brs"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "c" ("lang-c") => tree_sitter_c::LANGUAGE,
        extensions: ["c", "h"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen", "printf", "re2c"];
    #[cfg(corvane_src = "c3")]
    "c3" ("lang-c3") => c_language!(tree_sitter_c3),
        extensions: ["c3", "c3i", "c3t"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "c_sharp" ("lang-c-sharp") => tree_sitter_c_sharp::LANGUAGE,
        extensions: ["cs", "csx"],
        filenames: [],
        first_line: "",
        aliases: ["csharp", "cs", "c#"],
        injects: ["comment"];
    #[cfg(corvane_src = "cairo")]
    "cairo" ("lang-cairo") => c_language!(tree_sitter_cairo),
        extensions: ["cairo"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "python"];
    #[cfg(corvane_src = "capnp")]
    "capnp" ("lang-capnp") => c_language!(tree_sitter_capnp),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "chatito")]
    "chatito" ("lang-chatito") => c_language!(tree_sitter_chatito),
        extensions: ["chatito"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "circom")]
    "circom" ("lang-circom") => c_language!(tree_sitter_circom),
        extensions: ["circom"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "clojure")]
    "clojure" ("lang-clojure") => c_language!(tree_sitter_clojure),
        extensions: ["clj", "boot", "cl2", "cljc", "cljs", "cljs.hl", "cljscm", "cljx", "hic"],
        filenames: ["riemann.config"],
        first_line: r"^#!.*\b(bb)\b",
        aliases: [],
        injects: ["comment"];
    "cmake" ("lang-cmake") => tree_sitter_cmake::LANGUAGE,
        extensions: ["cmake"],
        filenames: ["cmakelists.txt"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "comment" ("lang-comment") => tree_sitter_comment::LANGUAGE,
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "commonlisp" ("lang-commonlisp") => tree_sitter_commonlisp::LANGUAGE_COMMONLISP,
        extensions: ["lisp", "lsp", "cl", "asd"],
        filenames: [],
        first_line: "",
        aliases: ["lisp", "common-lisp"],
        injects: ["comment"];
    #[cfg(corvane_src = "cooklang")]
    "cooklang" ("lang-cooklang") => c_language!(tree_sitter_cooklang),
        extensions: ["cook"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "corn")]
    "corn" ("lang-corn") => c_language!(tree_sitter_corn),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "cpon")]
    "cpon" ("lang-cpon") => c_language!(tree_sitter_cpon),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "cpp" ("lang-cpp") => tree_sitter_cpp::LANGUAGE,
        extensions: ["cc", "cpp", "cxx", "c++", "hpp", "hxx", "hh", "h++", "ipp", "tpp", "inl"],
        filenames: [],
        first_line: "",
        aliases: ["c++"],
        injects: ["comment", "doxygen", "printf", "re2c"];
    "css" ("lang-css") => tree_sitter_css::LANGUAGE,
        extensions: ["css"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "csv")]
    "csv" ("lang-csv") => c_language!(tree_sitter_csv),
        extensions: ["csv"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "cuda" ("lang-cuda") => tree_sitter_cuda::LANGUAGE,
        extensions: ["cu", "cuh"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen", "printf", "re2c"];
    #[cfg(corvane_src = "cue")]
    "cue" ("lang-cue") => c_language!(tree_sitter_cue),
        extensions: ["cue"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "cylc")]
    "cylc" ("lang-cylc") => c_language!(tree_sitter_cylc),
        extensions: ["cylc"],
        filenames: ["suite.rc"],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    "d" ("lang-d") => tree_sitter_d::LANGUAGE,
        extensions: ["d", "di"],
        filenames: [],
        first_line: "",
        aliases: ["dlang"],
        injects: ["comment", "printf"];
    "dart" ("lang-dart") => tree_sitter_dart::LANGUAGE,
        extensions: ["dart"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "desktop")]
    "desktop" ("lang-desktop") => c_language!(tree_sitter_desktop),
        extensions: ["desktop", "directory", "desktop.in"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    #[cfg(corvane_src = "devicetree")]
    "devicetree" ("lang-devicetree") => c_language!(tree_sitter_devicetree),
        extensions: ["dts", "dtsi", "dtso", "its", "overlay"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "dhall")]
    "dhall" ("lang-dhall") => c_language!(tree_sitter_dhall),
        extensions: ["dhall"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "diff" ("lang-diff") => tree_sitter_diff::LANGUAGE,
        extensions: ["diff", "patch"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "djot")]
    "djot" ("lang-djot") => c_language!(tree_sitter_djot),
        extensions: ["dj"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "dockerfile")]
    "dockerfile" ("lang-dockerfile") => c_language!(tree_sitter_dockerfile),
        extensions: ["dockerfile", "docker", "container", "containerfile"],
        filenames: ["dockerfile", "containerfile"],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    #[cfg(corvane_src = "dot")]
    "dot" ("lang-dot") => c_language!(tree_sitter_dot),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "html"];
    #[cfg(corvane_src = "doxygen")]
    "doxygen" ("lang-doxygen") => c_language!(tree_sitter_doxygen),
        extensions: ["doxygen"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["html"];
    "dtd" ("lang-xml") => tree_sitter_xml::LANGUAGE_DTD,
        extensions: ["dtd"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "earthfile")]
    "earthfile" ("lang-earthfile") => c_language!(tree_sitter_earthfile),
        extensions: [],
        filenames: ["earthfile"],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    #[cfg(corvane_src = "editorconfig")]
    "editorconfig" ("lang-editorconfig") => c_language!(tree_sitter_editorconfig),
        extensions: ["editorconfig"],
        filenames: ["editorconfig", ".editorconfig"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "eds")]
    "eds" ("lang-eds") => c_language!(tree_sitter_eds),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "eex")]
    "eex" ("lang-eex") => c_language!(tree_sitter_eex),
        extensions: ["html.eex", "leex"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["elixir"];
    "elisp" ("lang-elisp") => tree_sitter_elisp::LANGUAGE,
        extensions: ["el"],
        filenames: [".emacs", "_emacs"],
        first_line: "",
        aliases: ["emacs-lisp", "elisp"],
        injects: [];
    "elixir" ("lang-elixir") => tree_sitter_elixir::LANGUAGE,
        extensions: ["ex", "exs"],
        filenames: [],
        first_line: r"^#!.*\belixir\b",
        aliases: ["ex", "exs"],
        injects: ["comment", "eex", "heex", "json", "markdown", "regex", "surface", "zig"];
    "elm" ("lang-elm") => tree_sitter_elm::LANGUAGE,
        extensions: ["elm"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "glsl"];
    #[cfg(corvane_src = "elsa")]
    "elsa" ("lang-elsa") => c_language!(tree_sitter_elsa),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "elvish")]
    "elvish" ("lang-elvish") => c_language!(tree_sitter_elvish),
        extensions: ["elv"],
        filenames: [],
        first_line: r"^#!.*\b(elvish)\b",
        aliases: [],
        injects: ["comment"];
    "embedded_template" ("lang-embedded-template") => tree_sitter_embedded_template::LANGUAGE,
        extensions: ["erb", "ejs", "etlua", "rhtml"],
        filenames: [],
        first_line: "",
        aliases: ["erb", "ejs"],
        injects: ["html", "ruby"];
    #[cfg(corvane_src = "enforce")]
    "enforce" ("lang-enforce") => c_language!(tree_sitter_enforce),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen"];
    "erlang" ("lang-erlang") => tree_sitter_erlang::LANGUAGE,
        extensions: ["erl", "hrl", "escript", "app.src"],
        filenames: ["rebar.config"],
        first_line: r"^#!.*\bescript\b",
        aliases: ["erl"],
        injects: ["comment"];
    #[cfg(corvane_src = "facility")]
    "facility" ("lang-facility") => c_language!(tree_sitter_facility),
        extensions: ["fsd"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "markdown"];
    #[cfg(corvane_src = "faust")]
    "faust" ("lang-faust") => c_language!(tree_sitter_faust),
        extensions: ["dsp", "lib"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "fennel")]
    "fennel" ("lang-fennel") => c_language!(tree_sitter_fennel),
        extensions: ["fnl"],
        filenames: [],
        first_line: r"^#!.*\b(fennel)\b",
        aliases: [],
        injects: ["c", "comment", "luap", "printf", "query", "vim"];
    #[cfg(corvane_src = "fidl")]
    "fidl" ("lang-fidl") => c_language!(tree_sitter_fidl),
        extensions: ["fidl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "firrtl")]
    "firrtl" ("lang-firrtl") => c_language!(tree_sitter_firrtl),
        extensions: ["fir"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "fish" ("lang-fish") => c_language!(tree_sitter_fish),
        extensions: ["fish"],
        filenames: [],
        first_line: r"^#!.*\bfish\b",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "foam")]
    "foam" ("lang-foam") => c_language!(tree_sitter_foam),
        extensions: ["foam"],
        filenames: ["openfoam"],
        first_line: "",
        aliases: [],
        injects: ["comment", "cpp", "python", "regex"];
    #[cfg(corvane_src = "forth")]
    "forth" ("lang-forth") => c_language!(tree_sitter_forth),
        extensions: ["forth", "fth", "4th", "fr", "frt"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "fortran" ("lang-fortran") => tree_sitter_fortran::LANGUAGE,
        extensions: ["f", "f90", "f95", "f03", "f08", "for", "ftn", "f77"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "fsh")]
    "fsh" ("lang-fsh") => c_language!(tree_sitter_fsh),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "fsharp" ("lang-fsharp") => tree_sitter_fsharp::LANGUAGE_FSHARP,
        extensions: ["fs", "fsx", "fsscript"],
        filenames: [],
        first_line: "",
        aliases: ["f#", "fs"],
        injects: ["comment", "xml"];
    #[cfg(corvane_src = "func")]
    "func" ("lang-func") => c_language!(tree_sitter_func),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "gap")]
    "gap" ("lang-gap") => c_language!(tree_sitter_gap),
        extensions: ["g", "gi", "gap"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "gaptst")]
    "gaptst" ("lang-gaptst") => c_language!(tree_sitter_gaptst),
        extensions: ["tst"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "gap"];
    "gdscript" ("lang-gdscript") => tree_sitter_gdscript::LANGUAGE,
        extensions: ["gd"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "gdshader")]
    "gdshader" ("lang-gdshader") => c_language!(tree_sitter_gdshader),
        extensions: ["gdshader", "gdshaderinc"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "git_config")]
    "git_config" ("lang-git_config") => c_language!(tree_sitter_git_config),
        extensions: ["gitconfig"],
        filenames: [".gitconfig", ".gitmodules", ".tgitconfig", "config.worktree"],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    #[cfg(corvane_src = "git_rebase")]
    "git_rebase" ("lang-git_rebase") => c_language!(tree_sitter_git_rebase),
        extensions: ["git-rebase-todo"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    #[cfg(corvane_src = "gitattributes")]
    "gitattributes" ("lang-gitattributes") => c_language!(tree_sitter_gitattributes),
        extensions: ["gitattributes"],
        filenames: ["gitattributes", ".gitattributes"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "gitcommit" ("lang-gitcommit") => tree_sitter_gitcommit::LANGUAGE,
        extensions: [],
        filenames: ["commit_editmsg", "merge_msg", "tag_editmsg"],
        first_line: "",
        aliases: [],
        injects: ["diff", "git_rebase"];
    #[cfg(corvane_src = "gitignore")]
    "gitignore" ("lang-gitignore") => c_language!(tree_sitter_gitignore),
        extensions: ["gitignore"],
        filenames: [".agignore", ".atomignore", ".babelignore", ".bzrignore", ".ckignore", ".coffeelintignore", ".cvsignore", ".dockerignore", ".easignore", ".eleventyignore", ".eslint-ignore", ".eslintignore", ".gitignore", ".ignore", ".markdownlintignore", ".nodemonignore", ".npmignore", ".prettierignore", ".rgignore", ".stylelintignore", ".vercelignore", ".vscodeignore", "gitignore-global", "gitignore_global"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "gleam" ("lang-gleam") => tree_sitter_gleam::LANGUAGE,
        extensions: ["gleam"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "glimmer")]
    "glimmer" ("lang-glimmer") => c_language!(tree_sitter_glimmer),
        extensions: ["html.handlebars", "glimmer"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript"];
    #[cfg(corvane_src = "glimmer_javascript")]
    "glimmer_javascript" ("lang-glimmer_javascript") => c_language!(tree_sitter_glimmer_javascript),
        extensions: ["gjs", "javascript.glimmer"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["angular", "comment", "css", "glimmer", "graphql", "groq", "html", "jsdoc", "regex", "sql", "styled", "xml"];
    #[cfg(corvane_src = "glimmer_typescript")]
    "glimmer_typescript" ("lang-glimmer_typescript") => c_language!(tree_sitter_glimmer_typescript),
        extensions: ["gts", "typescript.glimmer"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["angular", "comment", "css", "glimmer", "graphql", "groq", "html", "jsdoc", "regex", "sql", "styled", "xml"];
    "glsl" ("lang-glsl") => tree_sitter_glsl::LANGUAGE_GLSL,
        extensions: ["glsl", "vert", "frag", "geom", "tesc", "tese", "comp", "rgen", "rchit", "rmiss", "mesh", "task"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen", "printf", "re2c"];
    #[cfg(corvane_src = "gn")]
    "gn" ("lang-gn") => c_language!(tree_sitter_gn),
        extensions: ["gn", "gni"],
        filenames: [".gn"],
        first_line: r"^#!.*\b(gn)\b",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "gnuplot")]
    "gnuplot" ("lang-gnuplot") => c_language!(tree_sitter_gnuplot),
        extensions: ["gnuplot", "gp", "gnu", "p", "plot", "plt"],
        filenames: [],
        first_line: r"^#!.*\b(gnuplot)\b",
        aliases: [],
        injects: ["comment"];
    "go" ("lang-go") => tree_sitter_go::LANGUAGE,
        extensions: ["go"],
        filenames: [],
        first_line: "",
        aliases: ["golang"],
        injects: ["comment", "printf", "re2c", "regex"];
    #[cfg(corvane_src = "goctl")]
    "goctl" ("lang-goctl") => c_language!(tree_sitter_goctl),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "godot_resource" ("lang-godot-resource") => tree_sitter_godot_resource::LANGUAGE,
        extensions: ["tscn", "tres", "godot"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "gomod")]
    "gomod" ("lang-gomod") => c_language!(tree_sitter_gomod),
        extensions: ["go.mod"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "gosum")]
    "gosum" ("lang-gosum") => c_language!(tree_sitter_gosum),
        extensions: ["go.sum"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "gotmpl")]
    "gotmpl" ("lang-gotmpl") => c_language!(tree_sitter_gotmpl),
        extensions: ["gohtml", "gotmpl", "html.tmpl", "tmpl", "tpl"],
        filenames: ["_helpers.tpl"],
        first_line: "",
        aliases: [],
        injects: ["comment", "html", "javascript", "printf"];
    #[cfg(corvane_src = "gowork")]
    "gowork" ("lang-gowork") => c_language!(tree_sitter_gowork),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "gpg")]
    "gpg" ("lang-gpg") => c_language!(tree_sitter_gpg),
        extensions: ["gpg.conf"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "graphql" ("lang-graphql") => tree_sitter_graphql::LANGUAGE,
        extensions: ["graphql", "graphqls", "gql"],
        filenames: [],
        first_line: "",
        aliases: ["gql"],
        injects: ["comment"];
    #[cfg(corvane_src = "gren")]
    "gren" ("lang-gren") => c_language!(tree_sitter_gren),
        extensions: ["gren"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "groovy")]
    "groovy" ("lang-groovy") => c_language!(tree_sitter_groovy),
        extensions: ["groovy", "grt", "gtpl", "gvy"],
        filenames: ["jenkinsfile"],
        first_line: r"^#!.*\b(groovy)\b",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "groq")]
    "groq" ("lang-groq") => c_language!(tree_sitter_groq),
        extensions: ["groq"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "gstlaunch")]
    "gstlaunch" ("lang-gstlaunch") => c_language!(tree_sitter_gstlaunch),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "hack")]
    "hack" ("lang-hack") => c_language!(tree_sitter_hack),
        extensions: ["hack", "hhi"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "handlebars" ("lang-handlebars") => tree_sitter_handlebars::LANGUAGE,
        extensions: ["hbs", "handlebars", "mustache"],
        filenames: [],
        first_line: "",
        aliases: ["hbs"],
        injects: [];
    #[cfg(corvane_src = "hare")]
    "hare" ("lang-hare") => c_language!(tree_sitter_hare),
        extensions: ["ha"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    "haskell" ("lang-haskell") => tree_sitter_haskell::LANGUAGE,
        extensions: ["hs", "hs-boot", "hsc"],
        filenames: [],
        first_line: r"^#!.*\b(runhaskell|stack|cabal)\b",
        aliases: ["hs"],
        injects: ["comment", "css", "graphql", "haskell_persistent", "html", "javascript", "json", "python", "sql", "typescript"];
    #[cfg(corvane_src = "haskell_persistent")]
    "haskell_persistent" ("lang-haskell_persistent") => c_language!(tree_sitter_haskell_persistent),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "hcl" ("lang-hcl") => tree_sitter_hcl::LANGUAGE,
        extensions: ["hcl", "nomad"],
        filenames: [],
        first_line: "",
        aliases: ["terraform", "tf"],
        injects: ["comment"];
    "heex" ("lang-heex") => tree_sitter_heex::LANGUAGE,
        extensions: ["heex"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "elixir"];
    #[cfg(corvane_src = "helm")]
    "helm" ("lang-helm") => c_language!(tree_sitter_helm),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "html", "javascript", "json", "printf", "regex", "yaml"];
    #[cfg(corvane_src = "hjson")]
    "hjson" ("lang-hjson") => c_language!(tree_sitter_hjson),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "hlsl" ("lang-hlsl") => tree_sitter_hlsl::LANGUAGE_HLSL,
        extensions: ["hlsl", "hlsli", "fx", "fxh", "usf", "ush"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen", "printf", "re2c"];
    #[cfg(corvane_src = "hocon")]
    "hocon" ("lang-hocon") => c_language!(tree_sitter_hocon),
        extensions: ["hocon"],
        filenames: [".scalafix.conf", ".scalafmt.conf"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "hoon")]
    "hoon" ("lang-hoon") => c_language!(tree_sitter_hoon),
        extensions: ["hoon"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "html" ("lang-html") => tree_sitter_html::LANGUAGE,
        extensions: ["html", "htm", "xhtml", "shtml"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript", "json", "python", "regex", "toml"];
    #[cfg(corvane_src = "htmldjango")]
    "htmldjango" ("lang-htmldjango") => c_language!(tree_sitter_htmldjango),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "html"];
    #[cfg(corvane_src = "http")]
    "http" ("lang-http") => c_language!(tree_sitter_http),
        extensions: ["http"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "graphql", "javascript", "json", "xml"];
    #[cfg(corvane_src = "hurl")]
    "hurl" ("lang-hurl") => c_language!(tree_sitter_hurl),
        extensions: ["hurl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "json", "xml"];
    #[cfg(corvane_src = "hyprlang")]
    "hyprlang" ("lang-hyprlang") => c_language!(tree_sitter_hyprlang),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    #[cfg(corvane_src = "idl")]
    "idl" ("lang-idl") => c_language!(tree_sitter_idl),
        extensions: ["idl", "pro", "dlm"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen"];
    #[cfg(corvane_src = "idris")]
    "idris" ("lang-idris") => c_language!(tree_sitter_idris),
        extensions: ["idr", "lidr"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "ini" ("lang-ini") => tree_sitter_ini::LANGUAGE,
        extensions: ["ini", "cfg", "inf"],
        filenames: [".npmrc"],
        first_line: "",
        aliases: ["dosini"],
        injects: ["comment"];
    #[cfg(corvane_src = "inko")]
    "inko" ("lang-inko") => c_language!(tree_sitter_inko),
        extensions: ["inko"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "ispc")]
    "ispc" ("lang-ispc") => c_language!(tree_sitter_ispc),
        extensions: ["ispc", "isph"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen", "printf", "re2c"];
    #[cfg(corvane_src = "janet_simple")]
    "janet_simple" ("lang-janet_simple") => c_language!(tree_sitter_janet_simple),
        extensions: ["cgen", "janet", "jdn"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "java" ("lang-java") => tree_sitter_java::LANGUAGE,
        extensions: ["java"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "javadoc", "printf"];
    #[cfg(corvane_src = "javadoc")]
    "javadoc" ("lang-javadoc") => c_language!(tree_sitter_javadoc),
        extensions: ["javadoc"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["html", "markdown_inline", "printf"];
    "javascript" ("lang-javascript") => tree_sitter_javascript::LANGUAGE,
        extensions: ["js", "mjs", "cjs", "jsx"],
        filenames: [],
        first_line: r"^#!.*\b(node|deno|bun)\b",
        aliases: ["js", "jsx", "node"],
        injects: ["angular", "comment", "css", "glimmer", "graphql", "groq", "html", "jsdoc", "regex", "sql", "styled", "xml"];
    "jinja" ("lang-jinja2") => tree_sitter_jinja2::LANGUAGE,
        extensions: ["jinja", "jinja2", "j2"],
        filenames: [],
        first_line: "",
        aliases: ["jinja2"],
        injects: [];
    #[cfg(corvane_src = "jinja_inline")]
    "jinja_inline" ("lang-jinja_inline") => c_language!(tree_sitter_jinja_inline),
        extensions: ["jinja_inline"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "jjdescription")]
    "jjdescription" ("lang-jjdescription") => c_language!(tree_sitter_jjdescription),
        extensions: ["jjdescription"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "diff"];
    #[cfg(corvane_src = "jq")]
    "jq" ("lang-jq") => c_language!(tree_sitter_jq),
        extensions: ["jq"],
        filenames: [],
        first_line: r"^#!.*\b(gojq|jaq|jq|jqjq|jqq|query\-json)\b",
        aliases: [],
        injects: ["comment", "regex"];
    "jsdoc" ("lang-jsdoc") => tree_sitter_jsdoc::LANGUAGE,
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "json" ("lang-json") => tree_sitter_json::LANGUAGE,
        extensions: ["json", "jsonc", "geojson", "webmanifest", "har", "code-workspace", "jsonl"],
        filenames: [".babelrc", ".eslintrc", ".prettierrc", "composer.lock", "flake.lock", ".swcrc"],
        first_line: "",
        aliases: ["jsonc"],
        injects: ["comment"];
    #[cfg(corvane_src = "json5")]
    "json5" ("lang-json5") => c_language!(tree_sitter_json5),
        extensions: ["json5"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "jsonnet" ("lang-jsonnet") => tree_sitter_jsonnet::LANGUAGE,
        extensions: ["jsonnet", "libsonnet"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "julia" ("lang-julia") => tree_sitter_julia::LANGUAGE,
        extensions: ["jl"],
        filenames: [],
        first_line: r"^#!.*\bjulia\b",
        aliases: ["jl"],
        injects: ["bash", "comment", "markdown", "regex"];
    #[cfg(corvane_src = "just")]
    "just" ("lang-just") => c_language!(tree_sitter_just),
        extensions: ["just", "justfile"],
        filenames: ["just", "justfile", ".justfile"],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment", "javascript", "python", "regex"];
    #[cfg(corvane_src = "kcl")]
    "kcl" ("lang-kcl") => c_language!(tree_sitter_kcl),
        extensions: ["k"],
        filenames: ["kcl.mod", "kcl.mod.lock"],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    #[cfg(corvane_src = "kconfig")]
    "kconfig" ("lang-kconfig") => c_language!(tree_sitter_kconfig),
        extensions: [],
        filenames: ["kconfig"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "kdl" ("lang-kdl") => tree_sitter_kdl::LANGUAGE,
        extensions: ["kdl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "kitty")]
    "kitty" ("lang-kitty") => c_language!(tree_sitter_kitty),
        extensions: ["kitty.conf"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    #[cfg(corvane_src = "kos")]
    "kos" ("lang-kos") => c_language!(tree_sitter_kos),
        extensions: ["kos"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "jsdoc"];
    "kotlin" ("lang-kotlin-ng") => tree_sitter_kotlin_ng::LANGUAGE,
        extensions: ["kt", "kts"],
        filenames: [],
        first_line: "",
        aliases: ["kt"],
        injects: ["comment"];
    #[cfg(corvane_src = "koto")]
    "koto" ("lang-koto") => c_language!(tree_sitter_koto),
        extensions: ["koto"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "kusto")]
    "kusto" ("lang-kusto") => c_language!(tree_sitter_kusto),
        extensions: ["csl", "kql"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "lalrpop")]
    "lalrpop" ("lang-lalrpop") => c_language!(tree_sitter_lalrpop),
        extensions: ["lalrpop"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex", "rust"];
    #[cfg(corvane_src = "ledger")]
    "ledger" ("lang-ledger") => c_language!(tree_sitter_ledger),
        extensions: ["ledger", "journal"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "leo")]
    "leo" ("lang-leo") => c_language!(tree_sitter_leo),
        extensions: ["leo"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "less" ("lang-less") => c_language!(tree_sitter_less),
        extensions: ["less"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "linkerscript")]
    "linkerscript" ("lang-linkerscript") => c_language!(tree_sitter_linkerscript),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "liquid")]
    "liquid" ("lang-liquid") => c_language!(tree_sitter_liquid),
        extensions: ["liquid"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "html", "javascript", "json", "yaml"];
    #[cfg(corvane_src = "liquidsoap")]
    "liquidsoap" ("lang-liquidsoap") => c_language!(tree_sitter_liquidsoap),
        extensions: ["liquidsoap", "liq"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "llvm" ("lang-llvm") => tree_sitter_llvm::LANGUAGE,
        extensions: ["ll"],
        filenames: [],
        first_line: "",
        aliases: ["llvm-ir"],
        injects: ["comment"];
    "lua" ("lang-lua") => tree_sitter_lua::LANGUAGE,
        extensions: ["lua"],
        filenames: [],
        first_line: r"^#!.*\blua",
        aliases: [],
        injects: ["c", "comment", "luadoc", "luap", "printf", "query", "vim"];
    #[cfg(corvane_src = "luadoc")]
    "luadoc" ("lang-luadoc") => c_language!(tree_sitter_luadoc),
        extensions: ["luadoc"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "luap")]
    "luap" ("lang-luap") => c_language!(tree_sitter_luap),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "luau" ("lang-luau") => tree_sitter_luau::LANGUAGE,
        extensions: ["luau"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["c", "comment", "luadoc", "luap"];
    #[cfg(corvane_src = "m68k")]
    "m68k" ("lang-m68k") => c_language!(tree_sitter_m68k),
        extensions: ["x68"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "make" ("lang-make") => tree_sitter_make::LANGUAGE,
        extensions: ["mk", "mak", "make"],
        filenames: ["makefile", "gnumakefile", "bsdmakefile"],
        first_line: "",
        aliases: ["makefile"],
        injects: ["bash", "comment"];
    "markdown" ("lang-md") => tree_sitter_md::LANGUAGE,
        extensions: ["md", "markdown", "mdown", "mkd", "mkdn", "mdwn", "ronn"],
        filenames: [],
        first_line: "",
        aliases: ["md"],
        injects: ["html", "markdown_inline", "toml", "yaml"];
    "markdown_inline" ("lang-md") => tree_sitter_md::INLINE_LANGUAGE,
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["html"];
    #[cfg(corvane_src = "matlab")]
    "matlab" ("lang-matlab") => c_language!(tree_sitter_matlab),
        extensions: ["matlab"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "menhir")]
    "menhir" ("lang-menhir") => c_language!(tree_sitter_menhir),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "ocaml"];
    #[cfg(corvane_src = "mermaid")]
    "mermaid" ("lang-mermaid") => c_language!(tree_sitter_mermaid),
        extensions: ["mmd", "mermaid"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "meson")]
    "meson" ("lang-meson") => c_language!(tree_sitter_meson),
        extensions: ["meson"],
        filenames: ["meson.build", "meson_options.txt"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "nasm")]
    "nasm" ("lang-nasm") => c_language!(tree_sitter_nasm),
        extensions: ["a51", "nas", "nasm"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "nginx" ("lang-nginx") => tree_sitter_nginx::LANGUAGE,
        extensions: ["nginx"],
        filenames: ["nginx.conf"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "nickel" ("lang-nickel") => tree_sitter_nickel::LANGUAGE,
        extensions: ["ncl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "nim")]
    "nim" ("lang-nim") => c_language!(tree_sitter_nim),
        extensions: ["nimble", "nims", "nim", "nim.cfg", "nimrod"],
        filenames: ["nim.cfg"],
        first_line: "",
        aliases: [],
        injects: ["markdown", "markdown_inline", "nim_format_string", "regex"];
    #[cfg(corvane_src = "nim_format_string")]
    "nim_format_string" ("lang-nim_format_string") => c_language!(tree_sitter_nim_format_string),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["nim"];
    #[cfg(corvane_src = "ninja")]
    "ninja" ("lang-ninja") => c_language!(tree_sitter_ninja),
        extensions: ["ninja"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "nix" ("lang-nix") => tree_sitter_nix::LANGUAGE,
        extensions: ["nix"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment", "fish", "haskell", "javascript", "lua", "python", "regex", "rust"];
    #[cfg(corvane_src = "nqc")]
    "nqc" ("lang-nqc") => c_language!(tree_sitter_nqc),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen", "printf", "re2c"];
    #[cfg(corvane_src = "nu")]
    "nu" ("lang-nu") => c_language!(tree_sitter_nu),
        extensions: ["nu"],
        filenames: ["nukefile"],
        first_line: r"^#!.*\b(nush)\b",
        aliases: [],
        injects: ["comment"];
    "objc" ("lang-objc") => tree_sitter_objc::LANGUAGE,
        extensions: ["m", "mm"],
        filenames: [],
        first_line: "",
        aliases: ["objective-c", "objectivec"],
        injects: ["comment", "doxygen", "printf", "re2c"];
    "ocaml" ("lang-ocaml") => tree_sitter_ocaml::LANGUAGE_OCAML,
        extensions: ["ml"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "ocaml_interface" ("lang-ocaml") => tree_sitter_ocaml::LANGUAGE_OCAML_INTERFACE,
        extensions: ["mli"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "ocaml_type" ("lang-ocaml") => tree_sitter_ocaml::LANGUAGE_OCAML_TYPE,
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "odin" ("lang-odin") => tree_sitter_odin::LANGUAGE,
        extensions: ["odin"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "pascal" ("lang-pascal") => tree_sitter_pascal::LANGUAGE,
        extensions: ["pas", "dpr", "lpr", "dpk"],
        filenames: [],
        first_line: "",
        aliases: ["delphi"],
        injects: ["asm", "comment"];
    #[cfg(corvane_src = "passwd")]
    "passwd" ("lang-passwd") => c_language!(tree_sitter_passwd),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "pem")]
    "pem" ("lang-pem") => c_language!(tree_sitter_pem),
        extensions: ["pem", "key", "crt", "cer", "csr"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "php" ("lang-php") => tree_sitter_php::LANGUAGE_PHP,
        extensions: ["php", "phtml", "php3", "php4", "php5", "php7", "phps"],
        filenames: [],
        first_line: r"^#!.*\bphp\b",
        aliases: [],
        injects: ["bash", "html", "phpdoc", "regex"];
    "php_only" ("lang-php") => tree_sitter_php::LANGUAGE_PHP_ONLY,
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "phpdoc", "regex"];
    #[cfg(corvane_src = "phpdoc")]
    "phpdoc" ("lang-phpdoc") => c_language!(tree_sitter_phpdoc),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "pioasm")]
    "pioasm" ("lang-pioasm") => c_language!(tree_sitter_pioasm),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["c", "comment"];
    #[cfg(corvane_src = "pkl")]
    "pkl" ("lang-pkl") => c_language!(tree_sitter_pkl),
        extensions: ["pcf", "pkl"],
        filenames: [],
        first_line: r"^#!.*\b(pkl)\b",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "po")]
    "po" ("lang-po") => c_language!(tree_sitter_po),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "poe_filter")]
    "poe_filter" ("lang-poe_filter") => c_language!(tree_sitter_poe_filter),
        extensions: ["filter"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "pony")]
    "pony" ("lang-pony") => c_language!(tree_sitter_pony),
        extensions: ["pony"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "powershell" ("lang-powershell") => tree_sitter_powershell::LANGUAGE,
        extensions: ["ps1", "psm1", "psd1"],
        filenames: [],
        first_line: r"^#!.*\bpwsh\b",
        aliases: ["ps1", "pwsh"],
        injects: ["comment", "regex"];
    "printf" ("lang-printf") => tree_sitter_printf::LANGUAGE,
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "prisma")]
    "prisma" ("lang-prisma") => c_language!(tree_sitter_prisma),
        extensions: ["prisma"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "promql")]
    "promql" ("lang-promql") => c_language!(tree_sitter_promql),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    "properties" ("lang-properties") => tree_sitter_properties::LANGUAGE,
        extensions: ["properties"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "proto" ("lang-proto") => tree_sitter_proto::LANGUAGE,
        extensions: ["proto"],
        filenames: [],
        first_line: "",
        aliases: ["protobuf"],
        injects: ["comment"];
    #[cfg(corvane_src = "prql")]
    "prql" ("lang-prql") => c_language!(tree_sitter_prql),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "json", "sql"];
    #[cfg(corvane_src = "psv")]
    "psv" ("lang-psv") => c_language!(tree_sitter_psv),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "pug")]
    "pug" ("lang-pug") => c_language!(tree_sitter_pug),
        extensions: ["jade", "pug"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "javascript"];
    #[cfg(corvane_src = "puppet")]
    "puppet" ("lang-puppet") => c_language!(tree_sitter_puppet),
        extensions: ["pp"],
        filenames: ["modulefile"],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    #[cfg(corvane_src = "purescript")]
    "purescript" ("lang-purescript") => c_language!(tree_sitter_purescript),
        extensions: ["^(purescript|purs)$", "purs"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "pymanifest")]
    "pymanifest" ("lang-pymanifest") => c_language!(tree_sitter_pymanifest),
        extensions: [],
        filenames: ["manifest.in"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "python" ("lang-python") => tree_sitter_python::LANGUAGE,
        extensions: ["py", "pyi", "pyw", "gyp", "wsgi"],
        filenames: ["sconstruct", "sconscript"],
        first_line: r"^#!.*\bpython[0-9.]*\b",
        aliases: ["py", "python3"],
        injects: ["comment", "printf", "regex"];
    "ql" ("lang-ql") => tree_sitter_ql::LANGUAGE,
        extensions: ["ql", "qll"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "qmldir")]
    "qmldir" ("lang-qmldir") => c_language!(tree_sitter_qmldir),
        extensions: ["qmldir"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "qmljs")]
    "qmljs" ("lang-qmljs") => c_language!(tree_sitter_qmljs),
        extensions: ["qml"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["angular", "comment", "css", "glimmer", "graphql", "groq", "html", "jsdoc", "regex", "sql", "styled", "xml"];
    #[cfg(corvane_src = "query")]
    "query" ("lang-query") => c_language!(tree_sitter_query),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "luap", "regex"];
    "r" ("lang-r") => tree_sitter_r::LANGUAGE,
        extensions: ["r", "rprofile"],
        filenames: [".rprofile"],
        first_line: r"^#!.*\bRscript\b",
        aliases: [],
        injects: ["comment"];
    "racket" ("lang-racket") => tree_sitter_racket::LANGUAGE,
        extensions: ["rkt", "rktl", "rktd", "scrbl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "rasi")]
    "rasi" ("lang-rasi") => c_language!(tree_sitter_rasi),
        extensions: ["rasi"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "razor")]
    "razor" ("lang-razor") => c_language!(tree_sitter_razor),
        extensions: ["razor", "cshtml"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "html"];
    #[cfg(corvane_src = "rbs")]
    "rbs" ("lang-rbs") => c_language!(tree_sitter_rbs),
        extensions: ["rbs"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "re2c")]
    "re2c" ("lang-re2c") => c_language!(tree_sitter_re2c),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "readline")]
    "readline" ("lang-readline") => c_language!(tree_sitter_readline),
        extensions: ["inputrc"],
        filenames: [".inputrc", "inputrc"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "regex" ("lang-regex") => tree_sitter_regex::LANGUAGE,
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "rego")]
    "rego" ("lang-rego") => c_language!(tree_sitter_rego),
        extensions: ["rego"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "requirements" ("lang-requirements") => tree_sitter_requirements::LANGUAGE,
        extensions: [],
        filenames: ["requirements.txt", "requirements-dev.txt", "constraints.txt"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "rescript")]
    "rescript" ("lang-rescript") => c_language!(tree_sitter_rescript),
        extensions: ["res", "resi"],
        filenames: [],
        first_line: r"^#!.*\b(ocaml)\b",
        aliases: [],
        injects: ["comment", "graphql", "javascript", "regex"];
    #[cfg(corvane_src = "rifleconf")]
    "rifleconf" ("lang-rifleconf") => c_language!(tree_sitter_rifleconf),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment", "regex"];
    #[cfg(corvane_src = "robot")]
    "robot" ("lang-robot") => c_language!(tree_sitter_robot),
        extensions: ["robot"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "robots_txt")]
    "robots_txt" ("lang-robots_txt") => c_language!(tree_sitter_robots_txt),
        extensions: ["robots"],
        filenames: ["robots.txt"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "roc")]
    "roc" ("lang-roc") => c_language!(tree_sitter_roc),
        extensions: ["roc"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "json"];
    #[cfg(corvane_src = "ron")]
    "ron" ("lang-ron") => c_language!(tree_sitter_ron),
        extensions: ["ron"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "rst" ("lang-rst") => tree_sitter_rst::LANGUAGE,
        extensions: ["rst", "rest"],
        filenames: [],
        first_line: "",
        aliases: ["restructuredtext"],
        injects: ["comment", "csv", "python"];
    "ruby" ("lang-ruby") => tree_sitter_ruby::LANGUAGE,
        extensions: ["rb", "rake", "gemspec", "ru", "rbw", "podspec", "thor", "jbuilder", "rabl"],
        filenames: ["gemfile", "rakefile", "podfile", "vagrantfile", "brewfile", "guardfile", "fastfile", "appfile", "capfile"],
        first_line: r"^#!.*\bruby\b",
        aliases: ["rb"],
        injects: ["comment", "rbs", "regex"];
    #[cfg(corvane_src = "runescript")]
    "runescript" ("lang-runescript") => c_language!(tree_sitter_runescript),
        extensions: ["rs2", "cs2"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "rust" ("lang-rust") => tree_sitter_rust::LANGUAGE,
        extensions: ["rs"],
        filenames: [],
        first_line: "",
        aliases: ["rs"],
        injects: ["comment", "re2c", "regex", "slint"];
    "scala" ("lang-scala") => tree_sitter_scala::LANGUAGE,
        extensions: ["scala", "sc", "sbt"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "scfg")]
    "scfg" ("lang-scfg") => c_language!(tree_sitter_scfg),
        extensions: ["scfg"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "scheme" ("lang-scheme") => tree_sitter_scheme::LANGUAGE,
        extensions: ["scm", "ss", "sld"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "scss" ("lang-scss") => c_language!(tree_sitter_scss),
        extensions: ["scss"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "sflog")]
    "sflog" ("lang-sflog") => c_language!(tree_sitter_sflog),
        extensions: ["sflog"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "slang")]
    "slang" ("lang-slang") => c_language!(tree_sitter_slang),
        extensions: ["slang"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "slim")]
    "slim" ("lang-slim") => c_language!(tree_sitter_slim),
        extensions: ["slim"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript", "less", "markdown", "ruby", "scss"];
    #[cfg(corvane_src = "slint")]
    "slint" ("lang-slint") => c_language!(tree_sitter_slint),
        extensions: ["slint"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "smali")]
    "smali" ("lang-smali") => c_language!(tree_sitter_smali),
        extensions: ["smali"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "smithy")]
    "smithy" ("lang-smithy") => c_language!(tree_sitter_smithy),
        extensions: ["smithy"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "snakemake")]
    "snakemake" ("lang-snakemake") => c_language!(tree_sitter_snakemake),
        extensions: ["smk", "snakefile"],
        filenames: ["snakefile"],
        first_line: "",
        aliases: [],
        injects: ["comment", "printf", "regex"];
    #[cfg(corvane_src = "snl")]
    "snl" ("lang-snl") => c_language!(tree_sitter_snl),
        extensions: ["st", "stt"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["c", "comment", "printf"];
    "solidity" ("lang-solidity") => tree_sitter_solidity::LANGUAGE,
        extensions: ["sol"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "doxygen"];
    #[cfg(corvane_src = "soql")]
    "soql" ("lang-soql") => c_language!(tree_sitter_soql),
        extensions: ["soql"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "sosl")]
    "sosl" ("lang-sosl") => c_language!(tree_sitter_sosl),
        extensions: ["sosl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "sourcepawn")]
    "sourcepawn" ("lang-sourcepawn") => c_language!(tree_sitter_sourcepawn),
        extensions: ["sp"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["jsdoc"];
    #[cfg(corvane_src = "sparql")]
    "sparql" ("lang-sparql") => c_language!(tree_sitter_sparql),
        extensions: ["sparql", "rq"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    #[cfg(corvane_src = "sproto")]
    "sproto" ("lang-sproto") => c_language!(tree_sitter_sproto),
        extensions: ["sproto"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "sql")]
    "sql" ("lang-sql") => c_language!(tree_sitter_sql),
        extensions: ["sql", "ddl", "mysql", "prc", "tab", "udf", "viw"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "squirrel")]
    "squirrel" ("lang-squirrel") => c_language!(tree_sitter_squirrel),
        extensions: ["nut"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "html"];
    #[cfg(corvane_src = "ssh_config")]
    "ssh_config" ("lang-ssh_config") => c_language!(tree_sitter_ssh_config),
        extensions: ["ssh_config"],
        filenames: ["ssh-config", "ssh_config", "sshconfig", "sshconfig.snip", "sshd-config", "sshd_config"],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    "starlark" ("lang-starlark") => tree_sitter_starlark::LANGUAGE,
        extensions: ["bzl", "star", "bazel"],
        filenames: ["build", "build.bazel", "workspace", "workspace.bazel", "module.bazel", "tiltfile"],
        first_line: "",
        aliases: ["bazel"],
        injects: ["comment", "printf"];
    #[cfg(corvane_src = "strace")]
    "strace" ("lang-strace") => c_language!(tree_sitter_strace),
        extensions: ["strace"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "styled")]
    "styled" ("lang-styled") => c_language!(tree_sitter_styled),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "supercollider")]
    "supercollider" ("lang-supercollider") => c_language!(tree_sitter_supercollider),
        extensions: ["scd"],
        filenames: [],
        first_line: r"^#!.*\b(sclang|scsynth)\b",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "superhtml")]
    "superhtml" ("lang-superhtml") => c_language!(tree_sitter_superhtml),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["css", "javascript"];
    #[cfg(corvane_src = "surface")]
    "surface" ("lang-surface") => c_language!(tree_sitter_surface),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "elixir"];
    "svelte" ("lang-svelte-ng") => tree_sitter_svelte_ng::LANGUAGE,
        extensions: ["svelte"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript", "json", "pug", "regex", "scss", "typescript"];
    "swift" ("lang-swift") => tree_sitter_swift::LANGUAGE,
        extensions: ["swift"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    #[cfg(corvane_src = "sxhkdrc")]
    "sxhkdrc" ("lang-sxhkdrc") => c_language!(tree_sitter_sxhkdrc),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    #[cfg(corvane_src = "systemtap")]
    "systemtap" ("lang-systemtap") => c_language!(tree_sitter_systemtap),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["c", "comment"];
    "systemverilog" ("lang-systemverilog") => tree_sitter_systemverilog::LANGUAGE,
        extensions: ["sv", "svh"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "verilog"];
    #[cfg(corvane_src = "t32")]
    "t32" ("lang-t32") => c_language!(tree_sitter_t32),
        extensions: ["cmm", "cmmt", "t32"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "tablegen")]
    "tablegen" ("lang-tablegen") => c_language!(tree_sitter_tablegen),
        extensions: ["td"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "cpp"];
    #[cfg(corvane_src = "tact")]
    "tact" ("lang-tact") => c_language!(tree_sitter_tact),
        extensions: ["tact"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "tcl")]
    "tcl" ("lang-tcl") => c_language!(tree_sitter_tcl),
        extensions: ["tk", "tcl", "tm", "adp", "sdc", "tcl.in", "xdc"],
        filenames: ["owh", "starfield"],
        first_line: r"^#!.*\b(tclsh|wish)\b",
        aliases: [],
        injects: ["comment"];
    "templ" ("lang-templ") => tree_sitter_templ::LANGUAGE,
        extensions: ["templ"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript", "re2c"];
    #[cfg(corvane_src = "tera")]
    "tera" ("lang-tera") => c_language!(tree_sitter_tera),
        extensions: ["tera"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "yaml"];
    #[cfg(corvane_src = "terraform")]
    "terraform" ("lang-terraform") => c_language!(tree_sitter_terraform),
        extensions: ["tf", "tfvars", "tofu", "workflow"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "textproto")]
    "textproto" ("lang-textproto") => c_language!(tree_sitter_textproto),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "thrift")]
    "thrift" ("lang-thrift") => c_language!(tree_sitter_thrift),
        extensions: ["thrift"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "tiger")]
    "tiger" ("lang-tiger") => c_language!(tree_sitter_tiger),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "tlaplus" ("lang-tlaplus") => tree_sitter_tlaplus::LANGUAGE,
        extensions: ["tla"],
        filenames: [],
        first_line: "",
        aliases: ["tla"],
        injects: ["comment"];
    #[cfg(corvane_src = "todotxt")]
    "todotxt" ("lang-todotxt") => c_language!(tree_sitter_todotxt),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "toml" ("lang-toml-ng") => tree_sitter_toml_ng::LANGUAGE,
        extensions: ["toml"],
        filenames: ["cargo.lock", "poetry.lock", "uv.lock", "pipfile"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "tsv")]
    "tsv" ("lang-tsv") => c_language!(tree_sitter_tsv),
        extensions: ["tsv", "vcf"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "tsx" ("lang-typescript") => tree_sitter_typescript::LANGUAGE_TSX,
        extensions: ["tsx", "mtsx", "ctsx"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["angular", "comment", "css", "glimmer", "graphql", "groq", "html", "jsdoc", "regex", "sql", "styled", "xml"];
    #[cfg(corvane_src = "turtle")]
    "turtle" ("lang-turtle") => c_language!(tree_sitter_turtle),
        extensions: ["ttl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "twig")]
    "twig" ("lang-twig") => c_language!(tree_sitter_twig),
        extensions: ["twig", "html.twig", "html.twig.js.css"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "html"];
    "typescript" ("lang-typescript") => tree_sitter_typescript::LANGUAGE_TYPESCRIPT,
        extensions: ["ts", "mts", "cts"],
        filenames: [],
        first_line: r"^#!.*\b(ts-node|tsx)\b",
        aliases: ["ts"],
        injects: ["angular", "comment", "css", "glimmer", "graphql", "groq", "html", "jsdoc", "regex", "sql", "styled", "xml"];
    #[cfg(corvane_src = "typespec")]
    "typespec" ("lang-typespec") => c_language!(tree_sitter_typespec),
        extensions: ["typespec", "tsp"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "typoscript")]
    "typoscript" ("lang-typoscript") => c_language!(tree_sitter_typoscript),
        extensions: ["typoscript", "tsconfig"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css"];
    #[cfg(corvane_src = "typst")]
    "typst" ("lang-typst") => c_language!(tree_sitter_typst),
        extensions: ["typ"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "udev")]
    "udev" ("lang-udev") => c_language!(tree_sitter_udev),
        extensions: ["rules"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["bash", "comment"];
    #[cfg(corvane_src = "ungrammar")]
    "ungrammar" ("lang-ungrammar") => c_language!(tree_sitter_ungrammar),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "uxntal")]
    "uxntal" ("lang-uxntal") => c_language!(tree_sitter_uxntal),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "v")]
    "v" ("lang-v") => c_language!(tree_sitter_v),
        extensions: ["vsh", "v.mod"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["c", "comment", "regex"];
    #[cfg(corvane_src = "vento")]
    "vento" ("lang-vento") => c_language!(tree_sitter_vento),
        extensions: ["vto"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "html", "javascript"];
    "verilog" ("lang-verilog") => tree_sitter_verilog::LANGUAGE,
        extensions: ["v", "vh"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "vhdl" ("lang-vhdl") => tree_sitter_vhdl::LANGUAGE,
        extensions: ["vhd", "vhdl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "vhs")]
    "vhs" ("lang-vhs") => c_language!(tree_sitter_vhs),
        extensions: ["tape"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "vim" ("lang-vim") => c_language!(tree_sitter_vim),
        extensions: ["vim"],
        filenames: [".vimrc", "_vimrc", ".gvimrc", "vimrc"],
        first_line: "",
        aliases: ["viml", "vimscript"],
        injects: ["comment", "lua", "python", "regex", "ruby"];
    #[cfg(corvane_src = "vimdoc")]
    "vimdoc" ("lang-vimdoc") => c_language!(tree_sitter_vimdoc),
        extensions: ["txt"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "vrl")]
    "vrl" ("lang-vrl") => c_language!(tree_sitter_vrl),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    #[cfg(corvane_src = "vue")]
    "vue" ("lang-vue") => c_language!(tree_sitter_vue),
        extensions: ["vue"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "css", "javascript", "json", "pug", "regex", "scss", "tsx", "typescript"];
    #[cfg(corvane_src = "wgsl")]
    "wgsl" ("lang-wgsl") => c_language!(tree_sitter_wgsl),
        extensions: ["wgsl"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "wgsl_bevy")]
    "wgsl_bevy" ("lang-wgsl_bevy") => c_language!(tree_sitter_wgsl_bevy),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "wing")]
    "wing" ("lang-wing") => c_language!(tree_sitter_wing),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    "wit" ("lang-wit") => c_language!(tree_sitter_wit),
        extensions: ["wit"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "wxml")]
    "wxml" ("lang-wxml") => c_language!(tree_sitter_wxml),
        extensions: ["wxml"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "javascript"];
    "xcompose" ("lang-xcompose") => tree_sitter_xcompose::LANGUAGE,
        extensions: [],
        filenames: [".xcompose", "xcompose"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "xml" ("lang-xml") => tree_sitter_xml::LANGUAGE_XML,
        extensions: ["xml", "svg", "xsd", "xslt", "xsl", "rng", "plist", "xaml", "csproj", "fsproj", "vbproj", "vcxproj", "props", "targets", "resx", "nuspec", "wsdl", "kml", "gpx", "storyboard", "xib", "entitlements"],
        filenames: [],
        first_line: r"^<\?xml",
        aliases: [],
        injects: ["comment", "css", "javascript", "sql"];
    #[cfg(corvane_src = "xresources")]
    "xresources" ("lang-xresources") => c_language!(tree_sitter_xresources),
        extensions: [],
        filenames: ["xdefaults", "xresources"],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    "yaml" ("lang-yaml") => tree_sitter_yaml::LANGUAGE,
        extensions: ["yml", "yaml"],
        filenames: [".clang-format", ".clang-tidy", ".gemrc"],
        first_line: "",
        aliases: ["yml"],
        injects: ["bash", "comment", "promql"];
    #[cfg(corvane_src = "yang")]
    "yang" ("lang-yang") => c_language!(tree_sitter_yang),
        extensions: ["yang"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "regex"];
    #[cfg(corvane_src = "yuck")]
    "yuck" ("lang-yuck") => c_language!(tree_sitter_yuck),
        extensions: ["yuck"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment", "jq", "regex"];
    "zig" ("lang-zig") => tree_sitter_zig::LANGUAGE,
        extensions: ["zig", "zon"],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: ["comment"];
    #[cfg(corvane_src = "ziggy")]
    "ziggy" ("lang-ziggy") => c_language!(tree_sitter_ziggy),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    #[cfg(corvane_src = "ziggy_schema")]
    "ziggy_schema" ("lang-ziggy_schema") => c_language!(tree_sitter_ziggy_schema),
        extensions: [],
        filenames: [],
        first_line: "",
        aliases: [],
        injects: [];
    "zsh" ("lang-zsh") => tree_sitter_zsh::LANGUAGE,
        extensions: ["zsh"],
        filenames: [".zshrc", ".zprofile", ".zshenv", ".zlogin", ".zlogout", "zshrc"],
        first_line: r"^#!.*\bzsh\b",
        aliases: [],
        injects: ["comment", "printf", "readline", "regex"];
}

/// Grammars in the `tree-sitter-rest` pack: those with a file type no
/// CodeMirror port covers, plus the languages they inject. The `rest` Cargo
/// feature enables exactly these (checked by corvane-highlight's tests).
pub const REST: &[&str] = &[
    "ada",
    "agda",
    "apex",
    "asciidoc",
    "asm",
    "awk",
    "bibtex",
    "bicep",
    "bitbake",
    "bp",
    "bpftrace",
    "brightscript",
    "c3",
    "cairo",
    "chatito",
    "circom",
    "comment",
    "commonlisp",
    "cooklang",
    "csv",
    "cuda",
    "cue",
    "cylc",
    "d",
    "desktop",
    "devicetree",
    "dhall",
    "djot",
    "doxygen",
    "dtd",
    "earthfile",
    "eex",
    "elisp",
    "elm",
    "elvish",
    "embedded_template",
    "erlang",
    "facility",
    "faust",
    "fennel",
    "fidl",
    "firrtl",
    "fish",
    "foam",
    "forth",
    "gap",
    "gaptst",
    "gdscript",
    "gdshader",
    "git_config",
    "git_rebase",
    "gitcommit",
    "gleam",
    "glimmer",
    "glimmer_javascript",
    "glimmer_typescript",
    "glsl",
    "gn",
    "gnuplot",
    "godot_resource",
    "gomod",
    "gosum",
    "gotmpl",
    "gpg",
    "graphql",
    "gren",
    "groovy",
    "groq",
    "hack",
    "handlebars",
    "hare",
    "haskell",
    "haskell_persistent",
    "hcl",
    "heex",
    "hlsl",
    "hocon",
    "hoon",
    "http",
    "hurl",
    "idl",
    "idris",
    "inko",
    "ispc",
    "janet_simple",
    "javadoc",
    "jinja",
    "jinja_inline",
    "jjdescription",
    "jq",
    "jsdoc",
    "json5",
    "jsonnet",
    "just",
    "kcl",
    "kconfig",
    "kdl",
    "kitty",
    "kos",
    "koto",
    "kusto",
    "lalrpop",
    "ledger",
    "leo",
    "liquid",
    "liquidsoap",
    "llvm",
    "luadoc",
    "luap",
    "m68k",
    "make",
    "markdown_inline",
    "matlab",
    "mermaid",
    "meson",
    "nasm",
    "nginx",
    "nickel",
    "nim",
    "nim_format_string",
    "ninja",
    "nix",
    "nu",
    "ocaml_interface",
    "odin",
    "pem",
    "pkl",
    "poe_filter",
    "pony",
    "printf",
    "prisma",
    "purescript",
    "pymanifest",
    "ql",
    "qmldir",
    "qmljs",
    "query",
    "racket",
    "rasi",
    "rbs",
    "re2c",
    "readline",
    "regex",
    "rego",
    "requirements",
    "rescript",
    "robot",
    "robots_txt",
    "roc",
    "ron",
    "runescript",
    "scfg",
    "sflog",
    "slang",
    "slint",
    "smali",
    "smithy",
    "snakemake",
    "solidity",
    "soql",
    "sosl",
    "sourcepawn",
    "sproto",
    "squirrel",
    "ssh_config",
    "starlark",
    "strace",
    "styled",
    "supercollider",
    "svelte",
    "systemverilog",
    "t32",
    "tablegen",
    "tact",
    "tcl",
    "templ",
    "tera",
    "terraform",
    "thrift",
    "tlaplus",
    "tsv",
    "turtle",
    "typespec",
    "typoscript",
    "typst",
    "udev",
    "v",
    "vento",
    "verilog",
    "vhdl",
    "vhs",
    "vim",
    "vimdoc",
    "wgsl",
    "wit",
    "wxml",
    "xcompose",
    "xresources",
    "yang",
    "yuck",
    "zsh",
];
