#!/usr/bin/env python3
"""Build one grammar-pack unit as a dynamic library with clang, without Rust:

    python3 tools/ts-queries/build_unit.py <unit> <out.dylib> [--target aarch64-apple-darwin]

A unit is a grammar package (`typescript`: typescript + tsx) or a grammar
built from source. The library holds the grammars' parser.c / scanner and a
generated C table with the same layout as corvane-grammars' (`ABI` 1,
`corvane_grammars_v1`), so the loader reads it like the compiled-in table. A
Rust cdylib would carry ~300 KB of std per unit; this carries none.

Sources: the locked crate (`cargo metadata`) or tools/ts-queries/fetch.py's
folder. Queries: crates/corvane-grammars/queries/<grammar>/.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import gen  # noqa: E402
import sync  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
QUERIES = ROOT / "crates" / "corvane-grammars" / "queries"
PACK_VERSION = re.search(
    r'"([0-9][^"]*)"',
    (ROOT / "crates" / "corvane-grammars" / "src" / "lib.rs").read_text().split("macro_rules! pack_version", 1)[1],
).group(1)


def c_string(text: str) -> str:
    """A C string literal, split into lines so compilers stay happy (`?` is
    escaped: `??=` is a trigraph in ISO C)."""
    out = []
    for line in text.splitlines(keepends=True):
        esc = line.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\r").replace("?", "\\?")
        esc = "".join(c if 32 <= ord(c) < 127 else "".join(f"\\{b:03o}" for b in c.encode()) for c in esc)
        out.append(f'"{esc}"')
    return "\n    ".join(out) if out else '""'


def crate_symbol(pkg_dir: Path, const: str) -> str:
    """The C function behind a `LanguageFn` constant of a grammar crate."""
    lib = (pkg_dir / "bindings" / "rust" / "lib.rs").read_text()
    m = re.search(rf"pub const {const}\s*:\s*LanguageFn\s*=\s*unsafe\s*\{{\s*LanguageFn::from_raw\((\w+)\)", lib)
    if not m:
        raise SystemExit(f"{pkg_dir.name}: no C function for {const}")
    return m.group(1)


def parser_dir(root: Path, symbol: str) -> Path:
    """The `src` folder whose parser.c defines `symbol`."""
    for parser in sorted(root.rglob("parser.c")):
        if re.search(rf"\b{symbol}\s*\(\s*(?:void)?\s*\)\s*\{{", parser.read_text(errors="replace")):
            return parser.parent
    raise SystemExit(f"no parser.c in {root} defines {symbol}")


def main(argv: list[str]) -> int:
    unit, out = argv[0], Path(argv[1])
    target = argv[argv.index("--target") + 1] if "--target" in argv else None
    languages = gen.load()
    grammars = sorted(n for n, l in languages.items() if gen.unit_of(n, l) == unit)
    if not grammars:
        raise SystemExit(f"no unit {unit}")
    pins = gen.lock()
    entries, externs, sources = [], [], []
    for name in grammars:
        lang = languages[name]
        if gen.is_source(lang):
            symbol = pins[name]["symbol"]
            root = sync.source_dir(name)
        else:
            root = sync.packages()[lang["package"]]["dir"]
            symbol = lang["symbol"] if "symbol" in lang else crate_symbol(root, lang["language"])
        src = parser_dir(root, symbol)
        sources.append(src)
        externs.append(f"extern const void *{symbol}(void);")
        read = lambda kind: (QUERIES / name / f"{kind}.scm").read_text()  # noqa: E731
        injects = sorted({n for t in gen.injected_names(name) if (n := gen.resolve(languages, t)) and n != name})
        lines = lambda xs: "".join(f"{x}\n" for x in xs)  # noqa: E731
        fields = [
            c_string(name),
            f"(const void *(*)(void)){symbol}",
            c_string(read("highlights")),
            c_string(read("injections")),
            c_string(read("locals")),
            c_string(lines(lang.get("extensions", []))),
            c_string(lines(lang.get("filenames", []))),
            c_string(lang.get("first_line", "")),
            c_string(lines(lang.get("aliases", []))),
            c_string(lines(injects)),
        ]
        entries.append("  {\n    " + ",\n    ".join(fields) + "\n  }")
    table = (
        "// Generated by tools/ts-queries/build_unit.py; the layout of corvane_grammars::Table (ABI 1).\n"
        "#include <stddef.h>\n#include <stdint.h>\n"
        "typedef struct { const char *name; const void *(*language)(void); const char *highlights;"
        " const char *injections; const char *locals; const char *extensions; const char *filenames;"
        " const char *first_line; const char *aliases; const char *injects; } Grammar;\n"
        "typedef struct { uint32_t abi; const char *version; size_t len; const Grammar *grammars; } Table;\n"
        + "\n".join(externs)
        + f"\nstatic const Grammar GRAMMARS[] = {{\n{','.join(entries)}\n}};\n"
        + f'static const Table TABLE = {{1, "{PACK_VERSION}", {len(entries)}, GRAMMARS}};\n'
        + '__attribute__((visibility("default"))) const Table *corvane_grammars_v1(void) { return &TABLE; }\n'
    )
    arch = ["-target", target.replace("-apple-darwin", "-apple-macos15.0")] if target else []
    with tempfile.TemporaryDirectory() as tmp:
        tmpd = Path(tmp)
        (tmpd / "table.c").write_text(table)
        objs, cpp = [tmpd / "table.o"], False
        cflags = ["-O2", "-fPIC", "-fvisibility=hidden", "-w", *arch]
        subprocess.run(["clang", "-c", "-std=c11", *cflags, str(tmpd / "table.c"), "-o", str(objs[0])], check=True)
        for i, src in enumerate(sources):
            for f in ["parser.c", "scanner.c", "scanner.cc"]:
                path = src / f
                if not path.exists():
                    continue
                obj = tmpd / f"{i}-{f}.o"
                if f.endswith(".cc"):
                    cpp = True
                    subprocess.run(["clang++", "-c", "-std=c++14", *cflags, "-I", str(src), str(path), "-o", str(obj)], check=True)
                else:
                    subprocess.run(["clang", "-c", "-std=c11", *cflags, "-I", str(src), str(path), "-o", str(obj)], check=True)
                objs.append(obj)
        out.parent.mkdir(parents=True, exist_ok=True)
        link = ["clang++" if cpp else "clang", "-dynamiclib", *arch, "-Wl,-dead_strip", "-Wl,-x",
                "-install_name", f"@rpath/{out.name}", *map(str, objs), "-o", str(out)]
        subprocess.run(link, check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
