#!/usr/bin/env python3
"""Write crates/corvane-grammars' Cargo.toml and src/grammars.rs from
tools/ts-queries/languages.toml.

    python3 tools/ts-queries/gen.py            # write
    python3 tools/ts-queries/gen.py --check    # fail if either file is stale

Run after sync.py: the `tree-sitter-rest` set follows the vendored injection
queries. A grammar is in it when none of its file types has a CodeMirror mode
(crates/corvane-highlight/src/cm/modes/mod.rs `mime_for_extension` /
`mime_for_basename`, the tables GitHub Desktop's highlighter uses), i.e. GHD
does not highlight the language at all, or when it has no file types and a
grammar in it injects it by name (comment, regex, jsdoc, …). corvane-highlight's tests check the same
rule against the real `cm_covers`.
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOOLS = ROOT / "tools" / "ts-queries"
CRATE = ROOT / "crates" / "corvane-grammars"
CM_MODES = ROOT / "crates" / "corvane-highlight" / "src" / "cm" / "modes" / "mod.rs"


def load() -> dict:
    with open(TOOLS / "languages.toml", "rb") as f:
        return tomllib.load(f)


def feature(package: str) -> str:
    return "lang-" + package.removeprefix("tree-sitter-")


def ident(package: str) -> str:
    return package.replace("-", "_")


def cm_tables() -> tuple[set[str], set[str]]:
    text = CM_MODES.read_text()

    def keys(fn: str) -> set[str]:
        body = text[text.index(f"pub fn {fn}(") :]
        body = body[: body.index("\n}\n")]
        return set(re.findall(r'^\s*"([^"]+)"\s*(?:\|[^=]*)?=>', body, re.M)) | set(
            re.findall(r'\|\s*"([^"]+)"', body)
        )

    return keys("mime_for_extension"), keys("mime_for_basename")


def cm_covers(file_type: str, is_filename: bool, exts: set[str], basenames: set[str]) -> bool:
    name = file_type if is_filename else f"x.{file_type}"
    if is_filename and name in basenames:
        return True
    dot = name.rfind(".")
    return dot >= 0 and name[dot:] in exts


def injected_names(name: str) -> set[str]:
    path = CRATE / "queries" / name / "injections.scm"
    if not path.exists():
        return set()
    text = "\n".join(line.split(";", 1)[0] if not line.lstrip().startswith(";") else "" for line in path.read_text().splitlines())
    return set(re.findall(r'injection\.language\s+"([^"]+)"', text))


def resolve(languages: dict, wanted: str) -> str | None:
    wanted = wanted.lower()
    for name, lang in languages.items():
        if name == wanted or wanted in lang.get("aliases", []):
            return name
    for name, lang in languages.items():
        if wanted in lang.get("extensions", []):
            return name
    return None


def rest_set(languages: dict) -> list[str]:
    exts, basenames = cm_tables()
    rest = set()
    for name, lang in languages.items():
        types = [(e, False) for e in lang.get("extensions", [])] + [(f, True) for f in lang.get("filenames", [])]
        if types and not any(cm_covers(t, f, exts, basenames) for t, f in types):
            rest.add(name)
    # plus the injection-only grammars they use (comment, regex, jsdoc, …),
    # transitively; languages GHD highlights stay out even when injected
    todo = list(rest)
    while todo:
        for target in injected_names(todo.pop()):
            name = resolve(languages, target)
            if name and name not in rest and injection_only(languages[name]):
                rest.add(name)
                todo.append(name)
    return sorted(rest)


def injection_only(lang: dict) -> bool:
    return not lang.get("extensions") and not lang.get("filenames")


def cargo_toml(languages: dict, rest: list[str]) -> str:
    packages: dict[str, str] = {}
    for lang in languages.values():
        packages[lang["package"]] = lang["version"]
    rest_features = sorted({feature(languages[n]["package"]) for n in rest})
    all_features = sorted(feature(p) for p in packages)

    def array(items: list[str], indent: str = "    ") -> str:
        return "[\n" + "".join(f'{indent}"{i}",\n' for i in items) + "]"

    lines = [
        "# Generated by tools/ts-queries/gen.py from tools/ts-queries/languages.toml; do not edit.",
        "[package]",
        'name = "corvane-grammars"',
        "version.workspace = true",
        "edition.workspace = true",
        "license.workspace = true",
        'description = "Tree-sitter grammars and highlight queries for Corvane\'s opt-in tree-sitter highlighter"',
        "",
        "[lib]",
        "# rlib: the \"full\" build links every grammar in; cdylib: the `tree-sitter-all`",
        "# / `tree-sitter-rest` packs (packaging/packs.sh), loaded with dlopen.",
        'crate-type = ["rlib", "cdylib"]',
        "",
        "# A grammar package may use `tree-sitter` itself only in a version that",
        "# resolves to corvane-highlight's (cargo refuses a second copy of the C",
        "# runtime: `links = \"tree-sitter\"`).",
        "[features]",
        "default = []",
        "# every grammar (the `tree-sitter-all` pack and the full build)",
        f"all = {array(all_features)}",
        "# grammars for file types no CodeMirror port covers, plus what they inject",
        "# (the `tree-sitter-rest` pack); `REST` in src/grammars.rs lists them",
        f"rest = {array(rest_features)}",
    ]
    for pkg in sorted(packages):
        lines.append(f'{feature(pkg)} = ["dep:{pkg}"]')
    lines += ["", "[dependencies]", "tree-sitter-language.workspace = true"]
    for pkg in sorted(packages):
        lines.append(f'{pkg} = {{ version = "={packages[pkg]}", optional = true }}')
    return "\n".join(lines) + "\n"


def rs_list(items: list[str]) -> str:
    return "[" + ", ".join(rs_str(i) for i in items) + "]"


def rs_str(s: str) -> str:
    if "\\" in s or '"' in s:
        return 'r"' + s + '"'
    return '"' + s + '"'


def grammars_rs(languages: dict, rest: list[str]) -> str:
    out = [
        "// Generated by tools/ts-queries/gen.py from tools/ts-queries/languages.toml; do not edit.",
        "",
    ]
    old = sorted({lang["package"] for lang in languages.values() if "symbol" in lang})
    for pkg in old:
        out.append(f'#[cfg(feature = "{feature(pkg)}")]')
        out.append(f"extern crate {ident(pkg)};")
    if old:
        out.append("")
    out.append("grammars! {")
    for name in sorted(languages):
        lang = languages[name]
        pkg = lang["package"]
        if "symbol" in lang:
            expr = f"c_language!({lang['symbol']})"
        else:
            expr = f"{ident(pkg)}::{lang['language']}"
        injects = sorted(
            {n for t in injected_names(name) if (n := resolve(languages, t)) and n != name}
        )
        out += [
            f'    "{name}" ("{feature(pkg)}") => {expr},',
            f"        extensions: {rs_list(lang.get('extensions', []))},",
            f"        filenames: {rs_list(lang.get('filenames', []))},",
            f"        first_line: {rs_str(lang.get('first_line', ''))},",
            f"        aliases: {rs_list(lang.get('aliases', []))},",
            f"        injects: {rs_list(injects)};",
        ]
    out.append("}")
    out.append("")
    out.append("/// Grammars in the `tree-sitter-rest` pack: those with a file type no")
    out.append("/// CodeMirror port covers, plus the languages they inject. The `rest` Cargo")
    out.append("/// feature enables exactly these (checked by corvane-highlight's tests).")
    out.append("pub const REST: &[&str] = &[")
    for name in rest:
        out.append(f'    "{name}",')
    out.append("];")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    languages = load()
    rest = rest_set(languages)
    files = {
        CRATE / "Cargo.toml": cargo_toml(languages, rest),
        CRATE / "src" / "grammars.rs": grammars_rs(languages, rest),
    }
    stale = []
    for path, text in files.items():
        if "--check" in argv:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text)
    if stale:
        print("stale (run tools/ts-queries/gen.py):\n  " + "\n  ".join(stale), file=sys.stderr)
        return 1
    if "--check" not in argv:
        print(f"{len(languages)} grammars, {len(rest)} in tree-sitter-rest")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
