1: 0+44=Comment
2: 0+13=Keyword
3: 0+5=Keyword
5: 0+2=Atom
6: 0+6=Atom
7: 0+6=Atom
8: 0+7=Atom 13+5=Variable 19+3=Variable 23+8=AltVariable 32+6=AltVariable 39+8=AltVariable 50+9=String 63+4=Variable 68+3=AltVariable
10: 0+7=Atom
11: 0+5=Atom
12: 0+7=Atom 24+7=String
13: 0+7=Atom 24+7=String 39+5=String 52+7=String
14: 0+6=Atom 13+5=String
16: 0+4=Keyword 8+5=String
17: 2+6=Atom
18: 0+4=Keyword
19: 2+6=Atom
20: 0+5=Keyword
22: 0+6=Variable 8+3=Variable 12+5=Variable 18+7=Variable 26+4=Variable
24: 0+3=Variable 7+6=String
26: 2+6=String 13+7=String 26+5=String
27: 3+2=String 9+7=String 18+2=Variable 22+1=String 25+1=String
29: 2+5=String 16+7=String 33+5=String
30: 1+1=String 2+4=Variable 7+10=String
31: 3+2=String 9+6=String 17+24=Variable 42+4=AltVariable 47+2=AltVariable 51+1=String 53+2=AltVariable 57+1=String
33: 2+5=String
34: 1+5=Variable 7+2=AltVariable 11+1=String
36: 0+4=Variable
37: 1+1=String 2+3=Keyword 6+1=Variable 8+2=Keyword 23+2=Keyword 26+4=Variable 31+5=String 40+4=Variable 48+4=Keyword
39: 0+7=Variable 11+6=String
40: 1+7=Variable 9+2=AltVariable 18+1=String 22+7=String 32+6=String 39+5=AltVariable
42: 0+5=Variable
43: 3+2=String 7+2=Variable 12+5=String
