//! GitHub Desktop dark theme (`app/styles/themes/_dark.scss`).

use super::primer::*;
use super::{Appearance, GhdTheme, c, ca};

pub fn theme() -> GhdTheme {
    GhdTheme {
        name: "GitHub Desktop Dark",
        appearance: Appearance::Dark,

        text: c(GRAY_100),
        text_secondary: c(GRAY_400),
        text_secondary_muted: c(GRAY_500_DARKEN_10),
        background: c(GRAY_900),
        box_background: c(GRAY_900_DARKEN_3),
        box_alt_background: c(GRAY_900_LIGHTEN_3),
        box_border: c(0x141414),
        box_border_contrast: c(GRAY_500_LIGHTEN_3),
        box_border_accent: c(BLUE),
        box_selected_background: c(GRAY_700),
        box_selected_text: c(GRAY_100),
        box_selected_active_background: c(BLUE),
        box_selected_active_text: c(WHITE),
        box_hover_background: c(GRAY_800),
        box_hover_text: c(GRAY_100),
        box_placeholder: c(GRAY_400),
        shadow: ca(0x000000, 0.5),
        overlay: ca(0x000000, 0.5),

        button_background: c(BLUE),
        button_hover_background: c(BLUE_LIGHTEN_5),
        button_text: c(WHITE),
        button_focus_border: c(BLUE_600),
        secondary_button_background: c(GRAY_800),
        secondary_button_border: c(GRAY_500_LIGHTEN_3),
        secondary_button_hover_background: c(GRAY_800),
        secondary_button_hover_border: c(GRAY_300),
        secondary_button_text: c(GRAY_100),
        link: c(LINK),
        link_hover: c(BLUE_LIGHTEN_3),

        toolbar_background: c(GRAY_900_DARKEN_3),
        toolbar_border: c(0x141414),
        toolbar_text: c(GRAY_100),
        toolbar_text_secondary: c(GRAY_400),
        toolbar_button_border: c(0x141414),
        toolbar_button_hover_background: c(GRAY_800),
        toolbar_button_hover_text: c(WHITE),
        toolbar_button_active_background: c(GRAY_900),
        toolbar_button_active_text: c(GRAY_100),
        toolbar_button_progress: c(GRAY_800),
        toolbar_badge_background: c(GRAY_700),
        toolbar_badge_active_background: c(GRAY_700),
        toolbar_dropdown_text_warning: c(ORANGE_600),

        tab_bar_active: c(BLUE),
        tab_bar_background: c(GRAY_900_DARKEN_3),
        tab_bar_hover_background: c(GRAY_800),
        tab_bar_count_text: c(GRAY_100),
        tab_bar_count_background: c(GRAY_700),
        list_item_hover_background: c(GRAY_800),
        list_item_badge_text: c(GRAY_100),
        list_item_badge_background: c(GRAY_600),
        list_item_selected_badge_text: c(WHITE),
        list_item_selected_badge_background: c(GRAY_500),
        list_item_selected_active_badge_text: c(GRAY_900),
        list_item_selected_active_badge_background: c(WHITE),
        scroll_bar_thumb: ca(0xffffff, 0.2),
        scroll_bar_thumb_active: ca(0xffffff, 0.5),

        focus: c(BLUE),
        accent: c(BLUE_200),
        text_field_focus_shadow: ca(BLUE, 0.25),
        primary_suggested_action_background: c(BLUE_900),
        primary_suggested_action_border: c(BLUE_700),
        suggested_action_icon: c(BLUE_400),
        control_background: c(0x3b3b3b),
        control_border: c(0x858585),
        control_disabled_background: c(0x3b3b3b),
        control_disabled_border: c(0x626262),
        control_disabled_accent: c(0x757575),
        control_disabled_glyph: c(0x3b3b3b),

        color_new: c(GREEN),
        color_deleted: c(RED),
        color_modified: c(YELLOW_700),
        color_renamed: c(BLUE),
        color_conflicted: c(ORANGE),

        co_author_tag_background: c(BLUE_800),
        co_author_tag_border: c(BLUE_700),
        input_icon_warning: c(YELLOW_600),
        input_icon_error: c(RED_400),
        input_icon_hover_background: c(GRAY_800),

        error: c(RED),
        form_error_background: c(RED_900_DARKEN_3),
        form_error_border: c(RED_900),
        form_error_text: c(GRAY_100),
        dialog_warning: c(YELLOW_600),
        dialog_information: c(BLUE_400),
        dialog_error: c(RED_600),
        dialog_banner_success_background: ca(0x165c26, 0.7),
        dialog_banner_success_border: c(GREEN_800),
        dialog_banner_success_text: c(GRAY_100),
        status_pending: c(YELLOW_700),
        status_error: c(RED_500),
        status_success: c(GREEN_500),
        tooltip_background: c(GRAY_800),
        tooltip_text: c(GRAY_100),
        menu_background: c(0x2c2c2e),
        menu_border: ca(0xffffff, 0.14),
        menu_text: c(0xffffff),
        menu_text_disabled: ca(0xffffff, 0.35),
        menu_highlight: c(0x2f6fdf),
        menu_highlight_text: c(0xffffff),
        syntax_variable: c(PURPLE_300),
        syntax_alt_variable: c(BLUE_300),
        syntax_keyword: c(RED_300),
        syntax_atom: c(BLUE_300),
        syntax_string: c(ORANGE_300),
        syntax_qualifier: c(PURPLE_300),
        syntax_type: c(RED_300),
        syntax_comment: c(GRAY_400),
        syntax_tag: c(GREEN_400),
        syntax_attribute: c(PURPLE_300),
        syntax_link: c(BLUE_300),
        syntax_header: c(RED_300),
        syntax_quote: c(GREEN_400),

        diff_text: c(GRAY_100),
        diff_alt_text: c(GRAY_100_DARKEN_20),
        diff_border: c(GRAY_800),
        diff_gutter: c(GRAY_800),
        diff_gutter_background: c(GRAY_900_DARKEN_3),
        diff_line_number: c(GRAY_400),
        diff_selected_background: c(BLUE_700),
        diff_selected_border: c(BLUE_600),
        diff_selected_gutter: c(BLUE_600),
        diff_selected_text: c(GRAY_100),
        diff_add_background: c(GREEN_900_DARKEN_3),
        diff_add_border: c(GREEN_900_DARKEN_2),
        diff_add_gutter: c(GREEN_900_DARKEN_2),
        diff_add_gutter_background: c(GREEN_900_DARKEN_8),
        diff_add_inner_background: c(GREEN_600),
        diff_add_text: c(GRAY_100),
        diff_delete_background: c(RED_900_DARKEN_15),
        diff_delete_border: c(RED_900_DARKEN_10),
        diff_delete_gutter: c(RED_900_DARKEN_10),
        diff_delete_gutter_background: c(RED_900_DARKEN_20),
        diff_delete_inner_background: c(RED_700),
        diff_delete_text: c(RED_100),
        diff_hunk_background: c(GRAY_900_DARKEN_3),
        diff_hunk_border: c(GRAY_900_LIGHTEN_3),
        diff_hunk_gutter: c(GRAY_900_LIGHTEN_3),
        diff_hunk_gutter_background: c(GRAY_900_DARKEN_6),
        diff_hunk_text: c(GRAY_400),
        diff_hover_background: c(BLUE_500),
        diff_hover_border: c(BLUE_400),
        diff_hover_gutter: c(BLUE_400),
        diff_hover_text: c(GRAY_100),
        diff_add_hover_background: c(GREEN_900),
        diff_add_hover_border: c(GREEN_700),
        diff_add_hover_gutter: c(GREEN_700),
        diff_add_hover_text: c(GRAY_100),
        diff_delete_hover_background: c(RED_800),
        diff_delete_hover_border: c(RED_700),
        diff_delete_hover_gutter: c(RED_700),
        diff_delete_hover_text: c(GRAY_100),
        diff_empty_row_background: c(GRAY_900_DARKEN_1),
        diff_empty_hunk_handle: c(GRAY_700),
    }
}
