//! GitHub Desktop light theme (`app/styles/_variables.scss` `:root`).

use super::primer::*;
use super::{Appearance, GhdTheme, c, ca};

pub fn theme() -> GhdTheme {
    GhdTheme {
        name: "GitHub Desktop Light",
        appearance: Appearance::Light,

        text: c(GRAY_900),
        text_secondary: c(GRAY_500),
        text_secondary_muted: c(GRAY_500_LIGHTEN_30),
        background: c(WHITE),
        box_background: c(WHITE),
        box_alt_background: c(GRAY_100),
        box_border: c(GRAY_200),
        box_border_contrast: c(GRAY_400_DARKEN_5),
        box_border_accent: c(BLUE),
        box_selected_background: c(0xebeef1),
        box_selected_text: c(GRAY_900),
        box_selected_active_background: c(BLUE),
        box_selected_active_text: c(WHITE),
        box_hover_background: c(GRAY_100),
        box_hover_text: c(GRAY_900),
        box_placeholder: c(GRAY_500),
        shadow: ca(0x47535f, 0.19),
        overlay: ca(0x000000, 0.4),

        button_background: c(BLUE),
        button_hover_background: c(BLUE_LIGHTEN_5),
        button_text: c(WHITE),
        button_focus_border: c(BLUE_100),
        secondary_button_background: c(GRAY_100),
        secondary_button_border: c(GRAY_400_DARKEN_5),
        secondary_button_hover_background: c(WHITE),
        secondary_button_hover_border: c(GRAY_400_DARKEN_5),
        secondary_button_text: c(GRAY_900),
        link: c(BLUE_LIGHTEN_5),
        link_hover: c(BLUE_600),

        toolbar_background: c(GRAY_900),
        toolbar_border: c(GRAY_900),
        toolbar_text: c(WHITE),
        toolbar_text_secondary: c(GRAY_300),
        toolbar_button_border: c(0x000000),
        toolbar_button_hover_background: c(GRAY_800),
        toolbar_button_hover_text: c(WHITE),
        toolbar_button_active_background: c(WHITE),
        toolbar_button_active_text: c(GRAY_900),
        toolbar_button_progress: c(GRAY_800),
        toolbar_badge_background: c(GRAY_600),
        toolbar_badge_active_background: c(GRAY_200),
        toolbar_dropdown_text_warning: c(ORANGE_800),

        tab_bar_active: c(BLUE),
        tab_bar_background: c(WHITE),
        tab_bar_hover_background: c(GRAY_100),
        tab_bar_count_text: c(GRAY_900),
        tab_bar_count_background: c(GRAY_200),
        list_item_hover_background: c(GRAY_100),
        list_item_badge_text: c(GRAY_800),
        list_item_badge_background: c(GRAY_200),
        list_item_selected_badge_text: c(GRAY_900),
        list_item_selected_badge_background: c(GRAY_300),
        list_item_selected_active_badge_text: c(GRAY_900),
        list_item_selected_active_badge_background: c(WHITE),
        scroll_bar_thumb: ca(0x000000, 0.2),
        scroll_bar_thumb_active: ca(0x000000, 0.5),

        focus: c(BLUE),
        accent: c(BLUE_400),
        text_field_focus_shadow: ca(BLUE, 0.25),
        primary_suggested_action_background: c(BLUE_000),
        primary_suggested_action_border: c(BLUE_200),
        suggested_action_icon: c(BLUE_400),
        control_background: c(WHITE),
        control_border: c(0x767676),
        control_disabled_background: c(0xf8f8f8),
        control_disabled_border: c(0xd1d1d1),
        control_disabled_accent: c(0xd1d1d1),
        control_disabled_glyph: c(0xededed),

        color_new: c(GREEN_600),
        color_deleted: c(RED_600),
        color_modified: c(YELLOW_700_DARKEN_10),
        color_renamed: c(BLUE),
        color_conflicted: c(ORANGE_800),

        co_author_tag_background: c(BLUE_000),
        co_author_tag_border: c(BLUE_200),
        input_icon_warning: c(YELLOW_800),
        input_icon_error: c(RED_600),
        input_icon_hover_background: c(GRAY_100),

        error: c(RED),
        form_error_background: c(RED_100),
        form_error_border: c(RED_200),
        form_error_text: c(RED_800),
        dialog_warning: c(YELLOW_800),
        dialog_information: c(BLUE_400),
        dialog_error: c(RED),
        dialog_banner_success_background: c(GREEN_100),
        dialog_banner_success_border: c(GREEN_300),
        dialog_banner_success_text: c(GREEN_800),
        status_pending: c(YELLOW_700),
        status_error: c(RED_500),
        status_success: c(0x1a7f37),
        tooltip_background: c(GRAY_800),
        tooltip_text: c(WHITE),
        menu_background: c(0xf3f3f3),
        menu_border: ca(0x000000, 0.18),
        menu_text: c(0x1d1d1f),
        menu_text_disabled: ca(0x000000, 0.3),
        menu_highlight: c(0x2f6fdf),
        menu_highlight_text: c(0xffffff),
        syntax_variable: c(0x6f42c1),
        syntax_alt_variable: c(0x24292e),
        syntax_keyword: c(0xd73a49),
        syntax_atom: c(0x005cc5),
        syntax_string: c(0x032f62),
        syntax_qualifier: c(0x6f42c1),
        syntax_type: c(0xd73a49),
        syntax_comment: c(GRAY_500),
        syntax_tag: c(0x22863a),
        syntax_attribute: c(0x6f42c1),
        syntax_link: c(0x032f62),
        syntax_header: c(0x0000ff),
        syntax_quote: c(0x1a7e31),

        diff_text: c(GRAY_900),
        diff_alt_text: c(GRAY_700),
        diff_border: c(GRAY_200),
        diff_gutter: c(GRAY_200),
        diff_gutter_background: c(WHITE),
        diff_line_number: c(GRAY_700),
        diff_selected_background: c(BLUE_400),
        diff_selected_border: c(BLUE_600),
        diff_selected_gutter: c(BLUE_600),
        diff_selected_text: c(WHITE),
        diff_add_background: c(GREEN_000_DARKEN_2),
        diff_add_border: c(GREEN_300),
        diff_add_gutter: c(GREEN_300),
        diff_add_gutter_background: c(GREEN_100_DARKEN_3),
        diff_add_inner_background: c(0xacf2bd),
        diff_add_text: c(GRAY_900),
        diff_delete_background: c(RED_000),
        diff_delete_border: c(RED_200),
        diff_delete_gutter: c(RED_200),
        diff_delete_gutter_background: c(RED_100),
        diff_delete_inner_background: c(0xfdb8c0),
        diff_delete_text: c(GRAY_900),
        diff_hunk_background: c(BLUE_000),
        diff_hunk_border: c(BLUE_200),
        diff_hunk_gutter: c(BLUE_200_DARKEN_5),
        diff_hunk_gutter_background: c(BLUE_100),
        diff_hunk_text: c(GRAY_600),
        diff_hover_background: c(BLUE_300),
        diff_hover_border: c(BLUE_400),
        diff_hover_gutter: c(BLUE_400),
        diff_hover_text: c(WHITE),
        diff_add_hover_background: c(GREEN_300),
        diff_add_hover_border: c(GREEN_400),
        diff_add_hover_gutter: c(GREEN_400),
        diff_add_hover_text: c(GRAY_900),
        diff_delete_hover_background: c(RED_200),
        diff_delete_hover_border: c(RED_300),
        diff_delete_hover_gutter: c(RED_300),
        diff_delete_hover_text: c(GRAY_900),
        diff_empty_row_background: c(GRAY_000),
        diff_empty_row_gutter_background: c(GRAY_000),
        file_warning_background: c(YELLOW_100),
        file_warning: c(YELLOW_700_DARKEN_10),
        file_warning_border: ca(YELLOW_700, 0.4),
        diff_empty_hunk_handle: c(GRAY_300),
    }
}
