// Kubernetes Deployment and Service generated from one config object.
local utils = import 'lib/utils.libsonnet';

/* Defaults shared by every environment. */
local defaults = {
  replicas: 2,
  image: 'registry.example.com/web',
  tag: 'latest',
  port: 8080,
  debug:: false,  // hidden field
  env: {},
};

local labels(name) = { app: name, 'app.kubernetes.io/managed-by': 'jsonnet' };

local deployment(name, cfg) = {
  apiVersion: 'apps/v1',
  kind: 'Deployment',
  metadata: { name: name, labels: labels(name) },
  spec: {
    replicas: if cfg.debug then 1 else cfg.replicas,
    selector: { matchLabels: labels(name) },
    template: {
      metadata: { labels: labels(name) },
      spec: { containers: [{
        name: name,
        image: '%s:%s' % [cfg.image, cfg.tag],
        ports: [{ containerPort: cfg.port }],
        env: [{ name: k, value: std.toString(cfg.env[k]) } for k in std.objectFields(cfg.env)],
      }] },
    },
  },
};

local config = defaults { tag: 'v1.4.2', env+: { LOG_LEVEL: "info\t", WORKERS: 4 } };

{
  assert config.replicas > 0 : 'replicas must be positive',
  'deployment.json': deployment('web', config),
  'service.json': { apiVersion: 'v1', kind: 'Service', spec: { ports: [{ port: 80, targetPort: config.port }] } },
  debugEnabled: config.debug || std.length(utils.flags) > 0,
  note: |||
    Generated by jsonnet; edit sample.jsonnet instead.
  |||,
}
