//! The tree-sitter grammar set (corvane-grammars) against the rest of the
//! highlighter: every query compiles and uses capture names `captures.rs`
//! knows, the `tree-sitter-rest` set is what GitHub Desktop does not
//! highlight, the languages reference is current, and the output on every
//! sample matches `tests/ts/expected` (`UPDATE_TS_GOLDEN=1` rewrites it).

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::sync::{Arc, OnceLock};

use corvane_highlight::treesitter::{self, Grammar, captures};

fn grammars() -> Vec<Arc<Grammar>> {
    static ONCE: OnceLock<()> = OnceLock::new();
    ONCE.get_or_init(|| {
        let table = corvane_grammars::corvane_grammars_v1().cast::<treesitter::ffi::Table>();
        // SAFETY: the compiled-in table lives for the whole process.
        unsafe { treesitter::register_table("bundled", table) }.expect("register");
    });
    treesitter::library::grammars()
}

fn root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

/// A path with `file_type` as extension or file name.
fn path_for(grammar: &Grammar, file_type: &str) -> String {
    if grammar.filenames.iter().any(|f| f == file_type) {
        file_type.to_string()
    } else {
        format!("x.{file_type}")
    }
}

fn ghd_covers(grammar: &Grammar) -> bool {
    grammar
        .extensions
        .iter()
        .chain(&grammar.filenames)
        .any(|t| corvane_highlight::cm_covers(&path_for(grammar, t), ""))
}

#[test]
fn every_query_compiles_with_known_captures() {
    let grammars = grammars();
    assert!(grammars.len() > 100, "{} grammars", grammars.len());
    let mut unknown = BTreeSet::new();
    for grammar in &grammars {
        if let Err(err) = treesitter::check_queries(grammar) {
            panic!("{}: {err}", grammar.name);
        }
        for name in grammar.capture_names() {
            if !captures::is_known(&name) {
                unknown.insert(format!("{} @{name}", grammar.name));
            }
        }
    }
    assert!(
        unknown.is_empty(),
        "capture names with no entry in captures.rs:\n{}",
        unknown.into_iter().collect::<Vec<_>>().join("\n")
    );
}

#[test]
fn the_rest_pack_is_what_github_desktop_does_not_highlight() {
    let grammars = grammars();
    let mut expected: BTreeSet<String> = grammars
        .iter()
        .filter(|g| !(g.extensions.is_empty() && g.filenames.is_empty()) && !ghd_covers(g))
        .map(|g| g.name.clone())
        .collect();
    // plus the injection-only grammars they use, transitively
    loop {
        let more: Vec<String> = grammars
            .iter()
            .filter(|g| expected.contains(&g.name))
            .flat_map(|g| g.injects.clone())
            .filter(|name| {
                grammars
                    .iter()
                    .any(|g| g.name == *name && g.extensions.is_empty() && g.filenames.is_empty())
            })
            .filter(|name| !expected.contains(name))
            .collect();
        if more.is_empty() {
            break;
        }
        expected.extend(more);
    }
    let actual: BTreeSet<String> = corvane_grammars::REST
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert_eq!(actual, expected, "rerun tools/ts-queries/gen.py");
}

#[test]
fn languages_doc() {
    let grammars = grammars();
    let rest: BTreeSet<&str> = corvane_grammars::REST.iter().copied().collect();
    let mut doc = String::from(
        "# Tree-sitter languages\n\n\
         Generated by `crates/corvane-highlight/tests/treesitter.rs` \
         (`UPDATE_TS_LANGUAGES_DOC=1 cargo test -p corvane-highlight --test treesitter languages_doc`) \
         from `tools/ts-queries/languages.toml`.\n\n\
         The grammars of Settings › Appearance › Syntax highlighting (flag \
         `105-tree-sitter-highlighting`). \"GHD\" marks languages GitHub Desktop's CodeMirror \
         modes already highlight: \"Tree-sitter for other languages\" keeps GHD's colours for \
         them, and the smaller `tree-sitter-rest` pack leaves them out.\n\n\
         | Grammar | Files | GHD | Rest pack | Queries |\n|---|---|---|---|---|\n",
    );
    for grammar in &grammars {
        let files: Vec<String> = grammar
            .extensions
            .iter()
            .map(|e| format!("`.{e}`"))
            .chain(grammar.filenames.iter().map(|f| format!("`{f}`")))
            .collect();
        let files = if files.is_empty() {
            "(injected only)".to_string()
        } else {
            files.join(" ")
        };
        let source = grammar
            .highlights
            .lines()
            .take(3)
            .find_map(|l| l.strip_prefix("; Source: "))
            .unwrap_or("")
            .to_string();
        doc.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            grammar.name,
            files,
            if ghd_covers(grammar) { "yes" } else { "" },
            if rest.contains(grammar.name.as_str()) {
                "yes"
            } else {
                ""
            },
            source
        ));
    }
    let path = root().join("../../.docs/tree-sitter-languages.md");
    if std::env::var_os("UPDATE_TS_LANGUAGES_DOC").is_some() {
        std::fs::write(&path, &doc).expect("write doc");
    }
    let Ok(current) = std::fs::read_to_string(&path) else {
        return;
    };
    assert!(
        current == doc,
        "{} is stale: UPDATE_TS_LANGUAGES_DOC=1 cargo test -p corvane-highlight --test treesitter languages_doc",
        path.display()
    );
}

fn samples() -> Vec<PathBuf> {
    let mut out = Vec::new();
    for dir in ["tests/cm/samples", "tests/ts/samples"] {
        if let Ok(entries) = std::fs::read_dir(root().join(dir)) {
            out.extend(entries.filter_map(|e| e.ok()).map(|e| e.path()));
        }
    }
    out.sort();
    out
}

/// `line: start+len=Class …` for every line with spans.
fn render(lines: &[&str], spans: &[Vec<corvane_highlight::Span>]) -> String {
    let mut out = String::new();
    for (ix, (line, spans)) in lines.iter().zip(spans).enumerate() {
        if spans.is_empty() {
            continue;
        }
        out.push_str(&format!("{}:", ix + 1));
        for span in spans {
            out.push_str(&format!(
                " {}+{}={:?}",
                span.range.start,
                span.range.len(),
                span.class
            ));
            debug_assert!(line.is_char_boundary(span.range.start));
        }
        out.push('\n');
    }
    out
}

#[test]
fn golden_spans() {
    grammars();
    let entries = treesitter::library::entries();
    let update = std::env::var_os("UPDATE_TS_GOLDEN").is_some();
    let expected_dir = root().join("tests/ts/expected");
    if update {
        std::fs::create_dir_all(&expected_dir).expect("expected dir");
    }
    let mut checked = 0;
    let mut stale = Vec::new();
    for sample in samples() {
        let name = sample
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or_default()
            .to_string();
        let Ok(text) = std::fs::read_to_string(&sample) else {
            continue;
        };
        let text = text.replace("\r\n", "\n");
        let lines: Vec<&str> = text.lines().collect();
        let first = lines.first().copied().unwrap_or("");
        if treesitter::detect::for_path(&entries, &name, first).is_none() {
            continue;
        }
        let spans = treesitter::highlight(&name, &lines, corvane_highlight::MAX_HIGHLIGHT_BYTES)
            .unwrap_or_else(|| panic!("{name}: no tree-sitter spans"));
        let got = render(&lines, &spans);
        let path = expected_dir.join(format!("{name}.spans"));
        if update {
            std::fs::write(&path, &got).expect("write golden");
        } else if std::fs::read_to_string(&path).ok().as_deref() != Some(got.as_str()) {
            stale.push(name);
        }
        checked += 1;
    }
    assert!(checked > 100, "only {checked} samples have a grammar");
    assert!(
        stale.is_empty(),
        "tree-sitter output changed for {stale:?}: review, then UPDATE_TS_GOLDEN=1 cargo test -p corvane-highlight --test treesitter golden_spans"
    );
}
