#!/usr/bin/env bash
# Build the on-demand pack archives and their manifest.
#
#   packaging/packs.sh [out-dir]        # default: target/release-assets/packs
#   PACKS=tree-sitter-all packaging/packs.sh   # only some (space-separated)
#
# Produces in <out>:
# - syntax-extended-<v>.zip: two-face's grammar collection as a syntect dump;
# - tree-sitter-{all,rest}-<v>-<os>-<arch>.zip: corvane-grammars as ad-hoc
#   signed dylibs on macOS, shared objects on Linux (every grammar / the ones
#   for languages GitHub Desktop does not highlight) plus the grammars' and
#   queries' licenses, one per architecture (the parse tables are ~170 MB per
#   architecture, so a universal file would double every download);
# - packs-manifest.json whose `url`s point at the GitHub release of the app
#   version in Cargo.toml. `release.sh` signs the manifest with minisign next
#   to the app assets.
#
# Grammars without a committed parser.c are generated by tree-sitter CLI
# 0.27.0 (CORVANE_TREE_SITTER=<path>, or `tree-sitter` on PATH; node runs their
# grammar.js). On macOS the dylibs are built for every macOS Rust target
# installed (`rustup target add x86_64-apple-darwin` for Intel packs; a
# warning names the missing one); on Linux for the build machine's
# architecture (release.yml builds each natively).
set -euo pipefail

# C grammars compile for the oldest macOS Corvane supports (Info.plist
# LSMinimumSystemVersion), not for the build machine's
export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-15.0}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/target/release-assets/packs}"
APP_VERSION="$(grep -m1 '^version' "$ROOT/Cargo.toml" | sed -E 's/.*"([^"]+)".*/\1/')"
# keep in sync with corvane_highlight::syntaxes::EXTENDED_PACK_VERSION
EXTENDED_VERSION="$(grep -m1 'EXTENDED_PACK_VERSION' "$ROOT/crates/corvane-highlight/src/syntaxes.rs" | sed -E 's/.*"([^"]+)".*/\1/')"
# corvane_grammars::PACK_VERSION (the `pack_version!` macro)
GRAMMARS_VERSION="$(grep -A3 'macro_rules! pack_version' "$ROOT/crates/corvane-grammars/src/lib.rs" | grep -m1 -oE '"[0-9][^"]*"' | tr -d '"')"
RELEASE_BASE="${RELEASE_BASE:-https://github.com/wasi-master/corvane/releases/download/v$APP_VERSION}"
PACKS="${PACKS:-syntax-extended tree-sitter-all tree-sitter-rest}"

mkdir -p "$OUT"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
ENTRIES="$WORK/entries.jsonl"
: > "$ENTRIES"

OS="$(uname -s)"
if [[ "$OS" == Darwin ]]; then
  PACK_OS=macos LIB_EXT=dylib
else
  PACK_OS=linux LIB_EXT=so
fi

# name version kind zip [target]
add_entry() {
  local sha size
  sha="$(python3 -c 'import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],"rb").read()).hexdigest())' "$4")"
  size="$(python3 -c 'import os,sys; print(os.path.getsize(sys.argv[1]))' "$4")"
  python3 - "$1" "$2" "$3" "$(basename "$4")" "$sha" "$size" "${5:-}" "$RELEASE_BASE" >> "$ENTRIES" <<'PY'
import json, sys
name, version, kind, file, sha, size, target, base = sys.argv[1:]
entry = {"name": name, "version": version, "min_app": "0.1.0", "url": f"{base}/{file}",
         "sha256": sha, "size": int(size), "kind": kind}
if target:
    entry["target"] = target
print(json.dumps(entry))
PY
  echo "built $4 ($size bytes, sha256 $sha)"
}

wants() { [[ " $PACKS " == *" $1 "* ]]; }

if wants syntax-extended; then
  echo "writing the extended grammar dump…"
  mkdir -p "$WORK/syntax-extended"
  (cd "$ROOT" && cargo run -q -p corvane-highlight --features pack-builder --example dump-extended -- "$WORK/syntax-extended/syntaxes.packdump")
  ZIP="$OUT/syntax-extended-$EXTENDED_VERSION.zip"
  rm -f "$ZIP"
  if [[ "$PACK_OS" == macos ]]; then
    (cd "$WORK/syntax-extended" && ditto -c -k . "$ZIP")
  else
    (cd "$WORK/syntax-extended" && zip -q -r -9 "$ZIP" .)
  fi
  add_entry syntax-extended "$EXTENDED_VERSION" syntax-extended "$ZIP"
fi

TARGETS=()
if [[ "$PACK_OS" == macos ]]; then
  for t in aarch64-apple-darwin x86_64-apple-darwin; do
    if rustup target list --installed 2>/dev/null | grep -qx "$t"; then
      TARGETS+=("$t")
    else
      echo "warning: $t is not installed; no tree-sitter packs for it" >&2
    fi
  done
else
  case "$(uname -m)" in
    x86_64) TARGETS=(x86_64-unknown-linux-gnu) ;;
    aarch64 | arm64) TARGETS=(aarch64-unknown-linux-gnu) ;;
    *) echo "warning: no tree-sitter packs for $(uname -m)" >&2 ;;
  esac
fi

# Every grammar unit (a grammar package, or a grammar built from source) is
# its own small library (tools/ts-queries/build_unit.py: clang, a generated C
# table, no Rust std), gzipped: an installed pack unpacks and opens only the
# units a diff needs (corvane_highlight::treesitter::load_pack). UNITS=<names>
# limits the build (testing).
build_units() {
  local t="$1" arch="${1%%-*}" unit lib out
  out="$WORK/units-$arch"
  mkdir -p "$out"
  BUILT=()
  for unit in ${UNITS:-$(python3 "$ROOT/tools/ts-queries/gen.py" --units all | cut -d' ' -f1)}; do
    lib="$out/$unit.$LIB_EXT"
    if ! python3 "$ROOT/tools/ts-queries/build_unit.py" "$unit" "$lib" --target "$t" 2>"$WORK/build-$unit.log"; then
      echo "warning: the $unit grammar did not build for $arch; left out:" >&2
      tail -3 "$WORK/build-$unit.log" >&2
      continue
    fi
    if [[ "$PACK_OS" == macos ]]; then
      # arm64 code must carry a signature; the linker's is kept, re-sign to be sure
      codesign --force --sign - --timestamp=none "$lib" 2>/dev/null
      nm -gU "$lib" | grep -q '_corvane_grammars_v1$' || { echo "$lib does not export corvane_grammars_v1" >&2; exit 1; }
    else
      nm -D --defined-only "$lib" | grep -q ' corvane_grammars_v1$' || { echo "$lib does not export corvane_grammars_v1" >&2; exit 1; }
    fi
    gzip -9 -n -c "$lib" > "$lib.gz"
    rm "$lib"
    BUILT+=("$unit")
  done
}

# variant (all | rest), arch
grammar_pack() {
  local variant="$1" arch="$2" dir zip unit
  dir="$WORK/tree-sitter-$variant-$arch"
  mkdir -p "$dir/grammars"
  for unit in $(python3 "$ROOT/tools/ts-queries/gen.py" --units "$variant" | cut -d' ' -f1); do
    [[ -f "$WORK/units-$arch/$unit.$LIB_EXT.gz" ]] && cp "$WORK/units-$arch/$unit.$LIB_EXT.gz" "$dir/grammars/"
  done
  python3 "$ROOT/tools/ts-queries/gen.py" --ext "$LIB_EXT" --index "$variant" "${BUILT[@]}" > "$dir/index.json"
  cp "$ROOT/crates/corvane-grammars/THIRD_PARTY.md" "$dir/THIRD_PARTY.md"
  zip="$OUT/tree-sitter-$variant-$GRAMMARS_VERSION-$PACK_OS-$arch.zip"
  rm -f "$zip"
  # the units are gzipped already: store them
  (cd "$dir" && zip -q -r -0 "$zip" grammars && zip -q -9 "$zip" index.json THIRD_PARTY.md)
  add_entry "tree-sitter-$variant" "$GRAMMARS_VERSION" "tree-sitter-$variant" "$zip" "$PACK_OS-$arch"
}

if wants tree-sitter-all || wants tree-sitter-rest; then
  python3 "$ROOT/tools/ts-queries/fetch.py" >/dev/null
  for t in "${TARGETS[@]}"; do
    echo "building the tree-sitter grammar units for ${t%%-*}…"
    build_units "$t"
    wants tree-sitter-all && grammar_pack all "${t%%-*}"
    wants tree-sitter-rest && grammar_pack rest "${t%%-*}"
  done
fi

python3 - "$ENTRIES" > "$OUT/packs-manifest.json" <<'PY'
import json, sys
packs = [json.loads(line) for line in open(sys.argv[1]) if line.strip()]
print(json.dumps({"schema": 1, "packs": packs}, indent=2))
PY
echo "manifest: $OUT/packs-manifest.json"
